// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createAttachmentForBooking = `-- name: CreateAttachmentForBooking :one
INSERT INTO attachments ("uploadedById", "bookingId", "filePath", "fileName", "fileType", "fileSize", description)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, "uploadedById", "vehicleId", "roomId", "bookingId", "filePath", "fileName", "fileType", "fileSize", description, "createdAt"
`

type CreateAttachmentForBookingParams struct {
	UploadedById int32          `json:"uploadedById"`
	BookingId    sql.NullInt32  `json:"bookingId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) CreateAttachmentForBooking(ctx context.Context, arg CreateAttachmentForBookingParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachmentForBooking,
		arg.UploadedById,
		arg.BookingId,
		arg.FilePath,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.Description,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploadedById,
		&i.VehicleId,
		&i.RoomId,
		&i.BookingId,
		&i.FilePath,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createAttachmentForRoom = `-- name: CreateAttachmentForRoom :one
INSERT INTO attachments ("uploadedById", "roomId", "filePath", "fileName", "fileType", "fileSize", description)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, "uploadedById", "vehicleId", "roomId", "bookingId", "filePath", "fileName", "fileType", "fileSize", description, "createdAt"
`

type CreateAttachmentForRoomParams struct {
	UploadedById int32          `json:"uploadedById"`
	RoomId       sql.NullInt32  `json:"roomId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) CreateAttachmentForRoom(ctx context.Context, arg CreateAttachmentForRoomParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachmentForRoom,
		arg.UploadedById,
		arg.RoomId,
		arg.FilePath,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.Description,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploadedById,
		&i.VehicleId,
		&i.RoomId,
		&i.BookingId,
		&i.FilePath,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createAttachmentForVehicle = `-- name: CreateAttachmentForVehicle :one
INSERT INTO attachments ("uploadedById", "vehicleId", "filePath", "fileName", "fileType", "fileSize", description)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, "uploadedById", "vehicleId", "roomId", "bookingId", "filePath", "fileName", "fileType", "fileSize", description, "createdAt"
`

type CreateAttachmentForVehicleParams struct {
	UploadedById int32          `json:"uploadedById"`
	VehicleId    sql.NullInt32  `json:"vehicleId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) CreateAttachmentForVehicle(ctx context.Context, arg CreateAttachmentForVehicleParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachmentForVehicle,
		arg.UploadedById,
		arg.VehicleId,
		arg.FilePath,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.Description,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploadedById,
		&i.VehicleId,
		&i.RoomId,
		&i.BookingId,
		&i.FilePath,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, id)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT a.id, a."uploadedById", a."vehicleId", a."roomId", a."bookingId", a."filePath", a."fileName", a."fileType", a."fileSize", a.description, a."createdAt", u.name AS uploader_name
FROM attachments a
JOIN users u ON u.id = a."uploadedById"
WHERE a.id = $1 LIMIT 1
`

type GetAttachmentByIDRow struct {
	ID           int32          `json:"id"`
	UploadedById int32          `json:"uploadedById"`
	VehicleId    sql.NullInt32  `json:"vehicleId"`
	RoomId       sql.NullInt32  `json:"roomId"`
	BookingId    sql.NullInt32  `json:"bookingId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"createdAt"`
	UploaderName string         `json:"uploader_name"`
}

func (q *Queries) GetAttachmentByID(ctx context.Context, id int32) (GetAttachmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentByID, id)
	var i GetAttachmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.UploadedById,
		&i.VehicleId,
		&i.RoomId,
		&i.BookingId,
		&i.FilePath,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Description,
		&i.CreatedAt,
		&i.UploaderName,
	)
	return i, err
}

const listAttachmentsByBooking = `-- name: ListAttachmentsByBooking :many
SELECT a.id, a."uploadedById", a."vehicleId", a."roomId", a."bookingId", a."filePath", a."fileName", a."fileType", a."fileSize", a.description, a."createdAt", u.name AS uploader_name
FROM attachments a
JOIN users u ON u.id = a."uploadedById"
WHERE a."bookingId" = $1
ORDER BY a."createdAt" DESC
`

type ListAttachmentsByBookingRow struct {
	ID           int32          `json:"id"`
	UploadedById int32          `json:"uploadedById"`
	VehicleId    sql.NullInt32  `json:"vehicleId"`
	RoomId       sql.NullInt32  `json:"roomId"`
	BookingId    sql.NullInt32  `json:"bookingId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"createdAt"`
	UploaderName string         `json:"uploader_name"`
}

func (q *Queries) ListAttachmentsByBooking(ctx context.Context, bookingid sql.NullInt32) ([]ListAttachmentsByBookingRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByBooking, bookingid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsByBookingRow
	for rows.Next() {
		var i ListAttachmentsByBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadedById,
			&i.VehicleId,
			&i.RoomId,
			&i.BookingId,
			&i.FilePath,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Description,
			&i.CreatedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByRoom = `-- name: ListAttachmentsByRoom :many
SELECT a.id, a."uploadedById", a."vehicleId", a."roomId", a."bookingId", a."filePath", a."fileName", a."fileType", a."fileSize", a.description, a."createdAt", u.name AS uploader_name
FROM attachments a
JOIN users u ON u.id = a."uploadedById"
WHERE a."roomId" = $1
ORDER BY a."createdAt" DESC
`

type ListAttachmentsByRoomRow struct {
	ID           int32          `json:"id"`
	UploadedById int32          `json:"uploadedById"`
	VehicleId    sql.NullInt32  `json:"vehicleId"`
	RoomId       sql.NullInt32  `json:"roomId"`
	BookingId    sql.NullInt32  `json:"bookingId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"createdAt"`
	UploaderName string         `json:"uploader_name"`
}

func (q *Queries) ListAttachmentsByRoom(ctx context.Context, roomid sql.NullInt32) ([]ListAttachmentsByRoomRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByRoom, roomid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsByRoomRow
	for rows.Next() {
		var i ListAttachmentsByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadedById,
			&i.VehicleId,
			&i.RoomId,
			&i.BookingId,
			&i.FilePath,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Description,
			&i.CreatedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByVehicle = `-- name: ListAttachmentsByVehicle :many
SELECT a.id, a."uploadedById", a."vehicleId", a."roomId", a."bookingId", a."filePath", a."fileName", a."fileType", a."fileSize", a.description, a."createdAt", u.name AS uploader_name
FROM attachments a
JOIN users u ON u.id = a."uploadedById"
WHERE a."vehicleId" = $1
ORDER BY a."createdAt" DESC
`

type ListAttachmentsByVehicleRow struct {
	ID           int32          `json:"id"`
	UploadedById int32          `json:"uploadedById"`
	VehicleId    sql.NullInt32  `json:"vehicleId"`
	RoomId       sql.NullInt32  `json:"roomId"`
	BookingId    sql.NullInt32  `json:"bookingId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"createdAt"`
	UploaderName string         `json:"uploader_name"`
}

func (q *Queries) ListAttachmentsByVehicle(ctx context.Context, vehicleid sql.NullInt32) ([]ListAttachmentsByVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByVehicle, vehicleid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsByVehicleRow
	for rows.Next() {
		var i ListAttachmentsByVehicleRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadedById,
			&i.VehicleId,
			&i.RoomId,
			&i.BookingId,
			&i.FilePath,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Description,
			&i.CreatedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
