// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package repository

import (
	"context"
	"database/sql"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs ("userId", action, "entityType", "entityId", description)
VALUES ($1, $2, $3, $4, $5) RETURNING id, "userId", action, "entityType", "entityId", description, "createdAt"
`

type CreateAuditLogParams struct {
	UserId      sql.NullInt32  `json:"userId"`
	Action      string         `json:"action"`
	EntityType  string         `json:"entityType"`
	EntityId    sql.NullInt32  `json:"entityId"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.UserId,
		arg.Action,
		arg.EntityType,
		arg.EntityId,
		arg.Description,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Action,
		&i.EntityType,
		&i.EntityId,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
