// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO password_reset_otps ("userId", "otpCode", "expiresAt", "isUsed")
VALUES ($1, $2, $3, FALSE)
RETURNING id, "userId", "otpCode", "expiresAt", "isUsed"
`

type CreateOTPParams struct {
	UserId    int32     `json:"userId"`
	OtpCode   string    `json:"otpCode"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (PasswordResetOtp, error) {
	row := q.db.QueryRowContext(ctx, createOTP, arg.UserId, arg.OtpCode, arg.ExpiresAt)
	var i PasswordResetOtp
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.OtpCode,
		&i.ExpiresAt,
		&i.IsUsed,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens ("userId", token, "expiresAt", revoked)
VALUES ($1, $2, $3, FALSE)
RETURNING id, "userId", token, "expiresAt", revoked
`

type CreateRefreshTokenParams struct {
	UserId    int32     `json:"userId"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.UserId, arg.Token, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, "userId", token, "expiresAt", revoked FROM refresh_tokens
WHERE token = $1 AND "userId" = $2 AND revoked = FALSE LIMIT 1
`

type GetRefreshTokenParams struct {
	Token  string `json:"token"`
	UserId int32  `json:"userId"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, arg.Token, arg.UserId)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u."employeeId", u.name, u.email, u.password, u."profilePhoto", u."isActive", u."roleId", u."departmentId", u."createdAt", u."updatedAt", r.name AS role_name, d.name AS department_name
FROM users u
JOIN roles r ON r.id = u."roleId"
JOIN departments d ON d.id = u."departmentId"
WHERE u.email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID             int32          `json:"id"`
	EmployeeId     string         `json:"employeeId"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Password       string         `json:"password"`
	ProfilePhoto   sql.NullString `json:"profilePhoto"`
	IsActive       bool           `json:"isActive"`
	RoleId         int32          `json:"roleId"`
	DepartmentId   int32          `json:"departmentId"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	RoleName       RoleName       `json:"role_name"`
	DepartmentName string         `json:"department_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.DepartmentName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u."employeeId", u.name, u.email, u.password, u."profilePhoto", u."isActive", u."roleId", u."departmentId", u."createdAt", u."updatedAt", r.name AS role_name, d.name AS department_name
FROM users u
JOIN roles r ON r.id = u."roleId"
JOIN departments d ON d.id = u."departmentId"
WHERE u.id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID             int32          `json:"id"`
	EmployeeId     string         `json:"employeeId"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Password       string         `json:"password"`
	ProfilePhoto   sql.NullString `json:"profilePhoto"`
	IsActive       bool           `json:"isActive"`
	RoleId         int32          `json:"roleId"`
	DepartmentId   int32          `json:"departmentId"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	RoleName       RoleName       `json:"role_name"`
	DepartmentName string         `json:"department_name"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleName,
		&i.DepartmentName,
	)
	return i, err
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, "userId", "otpCode", "expiresAt", "isUsed" FROM password_reset_otps
WHERE "userId" = $1 AND "otpCode" = $2 AND "isUsed" = FALSE
ORDER BY id DESC LIMIT 1
`

type GetValidOTPParams struct {
	UserId  int32  `json:"userId"`
	OtpCode string `json:"otpCode"`
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (PasswordResetOtp, error) {
	row := q.db.QueryRowContext(ctx, getValidOTP, arg.UserId, arg.OtpCode)
	var i PasswordResetOtp
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.OtpCode,
		&i.ExpiresAt,
		&i.IsUsed,
	)
	return i, err
}

const invalidatePreviousOTPs = `-- name: InvalidatePreviousOTPs :exec
UPDATE password_reset_otps SET "isUsed" = TRUE
WHERE "userId" = $1 AND "isUsed" = FALSE
`

func (q *Queries) InvalidatePreviousOTPs(ctx context.Context, userid int32) error {
	_, err := q.db.ExecContext(ctx, invalidatePreviousOTPs, userid)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE password_reset_otps SET "isUsed" = TRUE WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markOTPUsed, id)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = TRUE
WHERE token = $1 AND "userId" = $2
`

type RevokeRefreshTokenParams struct {
	Token  string `json:"token"`
	UserId int32  `json:"userId"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.Token, arg.UserId)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $1, "updatedAt" = NOW() WHERE id = $2
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	ID       int32  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}
