// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const approveBooking = `-- name: ApproveBooking :one
UPDATE bookings
SET status = 'APPROVED', "approvedById" = $2, "approvedAt" = NOW(), "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

type ApproveBookingParams struct {
	ID           int32         `json:"id"`
	ApprovedById sql.NullInt32 `json:"approvedById"`
}

func (q *Queries) ApproveBooking(ctx context.Context, arg ApproveBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, approveBooking, arg.ID, arg.ApprovedById)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const assignVehicleToBooking = `-- name: AssignVehicleToBooking :one
UPDATE bookings
SET "assignedDriverId" = $2, "assignedVehicleId" = $3, "assignedAt" = NOW(), "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

type AssignVehicleToBookingParams struct {
	ID                int32         `json:"id"`
	AssignedDriverId  sql.NullInt32 `json:"assignedDriverId"`
	AssignedVehicleId sql.NullInt32 `json:"assignedVehicleId"`
}

func (q *Queries) AssignVehicleToBooking(ctx context.Context, arg AssignVehicleToBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, assignVehicleToBooking, arg.ID, arg.AssignedDriverId, arg.AssignedVehicleId)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings SET status = 'CANCELLED', "updatedAt" = NOW() WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

func (q *Queries) CancelBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRowContext(ctx, cancelBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const checkBookingConflict = `-- name: CheckBookingConflict :one
SELECT COUNT(*) FROM bookings
WHERE "resourceId" = $1
  AND status IN ('PENDING', 'APPROVED', 'ONGOING')
  AND "startDate" < $3
  AND "endDate" > $2
  AND ($4::int IS NULL OR id != $4::int)
`

type CheckBookingConflictParams struct {
	ResourceId int32         `json:"resourceId"`
	EndDate    time.Time     `json:"endDate"`
	StartDate  time.Time     `json:"startDate"`
	ExcludeID  sql.NullInt32 `json:"exclude_id"`
}

func (q *Queries) CheckBookingConflict(ctx context.Context, arg CheckBookingConflictParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkBookingConflict,
		arg.ResourceId,
		arg.EndDate,
		arg.StartDate,
		arg.ExcludeID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkVehicleConflict = `-- name: CheckVehicleConflict :one
SELECT COUNT(*) FROM bookings
WHERE "assignedVehicleId" = $1
  AND status IN ('APPROVED', 'ONGOING')
  AND "startDate" < $3
  AND "endDate" > $2
  AND id != $4
`

type CheckVehicleConflictParams struct {
	AssignedVehicleId sql.NullInt32 `json:"assignedVehicleId"`
	EndDate           time.Time     `json:"endDate"`
	StartDate         time.Time     `json:"startDate"`
	ID                int32         `json:"id"`
}

func (q *Queries) CheckVehicleConflict(ctx context.Context, arg CheckVehicleConflictParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkVehicleConflict,
		arg.AssignedVehicleId,
		arg.EndDate,
		arg.StartDate,
		arg.ID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const completeBooking = `-- name: CompleteBooking :one
UPDATE bookings
SET status = 'COMPLETED', "returnedAt" = NOW(), "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

func (q *Queries) CompleteBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRowContext(ctx, completeBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const countBookings = `-- name: CountBookings :one
SELECT COUNT(*) FROM bookings b
JOIN users u ON u.id = b."userId"
JOIN resources r ON r.id = b."resourceId"
WHERE ($1::int IS NULL OR b."userId" = $1::int)
  AND ($2::booking_status IS NULL OR b.status = $2::booking_status)
  AND ($3::int IS NULL OR b."resourceId" = $3::int)
  AND ($4::resource_type IS NULL OR r.type = $4::resource_type)
  AND ($5::int IS NULL OR b."assignedDriverId" = $5::int)
  AND ($6::timestamptz IS NULL OR b."startDate" >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR b."endDate" <= $7::timestamptz)
  AND ($8::text IS NULL OR r.name ILIKE '%' || $8::text || '%' OR u.name ILIKE '%' || $8::text || '%')
`

type CountBookingsParams struct {
	UserID       sql.NullInt32     `json:"user_id"`
	Status       NullBookingStatus `json:"status"`
	ResourceID   sql.NullInt32     `json:"resource_id"`
	ResourceType NullResourceType  `json:"resource_type"`
	DriverID     sql.NullInt32     `json:"driver_id"`
	StartFrom    sql.NullTime      `json:"start_from"`
	EndTo        sql.NullTime      `json:"end_to"`
	Search       sql.NullString    `json:"search"`
}

func (q *Queries) CountBookings(ctx context.Context, arg CountBookingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookings,
		arg.UserID,
		arg.Status,
		arg.ResourceID,
		arg.ResourceType,
		arg.DriverID,
		arg.StartFrom,
		arg.EndTo,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalLog = `-- name: CreateApprovalLog :one
INSERT INTO approval_logs ("bookingId", "approverId", action, note)
VALUES ($1, $2, $3, $4) RETURNING id, "bookingId", "approverId", action, note, "createdAt"
`

type CreateApprovalLogParams struct {
	BookingId  int32          `json:"bookingId"`
	ApproverId int32          `json:"approverId"`
	Action     ApprovalAction `json:"action"`
	Note       sql.NullString `json:"note"`
}

func (q *Queries) CreateApprovalLog(ctx context.Context, arg CreateApprovalLogParams) (ApprovalLog, error) {
	row := q.db.QueryRowContext(ctx, createApprovalLog,
		arg.BookingId,
		arg.ApproverId,
		arg.Action,
		arg.Note,
	)
	var i ApprovalLog
	err := row.Scan(
		&i.ID,
		&i.BookingId,
		&i.ApproverId,
		&i.Action,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    "userId", "resourceId", "startDate", "endDate", purpose, 
    "passengerCount", "assignedDriverId", "assignedVehicleId", status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'PENDING') RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

type CreateBookingParams struct {
	UserId            int32         `json:"userId"`
	ResourceId        int32         `json:"resourceId"`
	StartDate         time.Time     `json:"startDate"`
	EndDate           time.Time     `json:"endDate"`
	Purpose           string        `json:"purpose"`
	PassengerCount    int32         `json:"passengerCount"`
	AssignedDriverId  sql.NullInt32 `json:"assignedDriverId"`
	AssignedVehicleId sql.NullInt32 `json:"assignedVehicleId"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.UserId,
		arg.ResourceId,
		arg.StartDate,
		arg.EndDate,
		arg.Purpose,
		arg.PassengerCount,
		arg.AssignedDriverId,
		arg.AssignedVehicleId,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const createDriverRating = `-- name: CreateDriverRating :one
INSERT INTO driver_ratings ("bookingId", "driverId", "ratedById", rating, review)
VALUES ($1, $2, $3, $4, $5) RETURNING id, "bookingId", "driverId", "ratedById", rating, review, "createdAt"
`

type CreateDriverRatingParams struct {
	BookingId int32          `json:"bookingId"`
	DriverId  int32          `json:"driverId"`
	RatedById int32          `json:"ratedById"`
	Rating    int16          `json:"rating"`
	Review    sql.NullString `json:"review"`
}

func (q *Queries) CreateDriverRating(ctx context.Context, arg CreateDriverRatingParams) (DriverRating, error) {
	row := q.db.QueryRowContext(ctx, createDriverRating,
		arg.BookingId,
		arg.DriverId,
		arg.RatedById,
		arg.Rating,
		arg.Review,
	)
	var i DriverRating
	err := row.Scan(
		&i.ID,
		&i.BookingId,
		&i.DriverId,
		&i.RatedById,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalLogs = `-- name: GetApprovalLogs :many
SELECT al.id, al."bookingId", al."approverId", al.action, al.note, al."createdAt", u.name AS approver_name
FROM approval_logs al
JOIN users u ON u.id = al."approverId"
WHERE al."bookingId" = $1
ORDER BY al."createdAt" ASC
`

type GetApprovalLogsRow struct {
	ID           int32          `json:"id"`
	BookingId    int32          `json:"bookingId"`
	ApproverId   int32          `json:"approverId"`
	Action       ApprovalAction `json:"action"`
	Note         sql.NullString `json:"note"`
	CreatedAt    time.Time      `json:"createdAt"`
	ApproverName string         `json:"approver_name"`
}

func (q *Queries) GetApprovalLogs(ctx context.Context, bookingid int32) ([]GetApprovalLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getApprovalLogs, bookingid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApprovalLogsRow
	for rows.Next() {
		var i GetApprovalLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingId,
			&i.ApproverId,
			&i.Action,
			&i.Note,
			&i.CreatedAt,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT b.id, b."userId", b."resourceId", b."startDate", b."endDate", b.purpose, b."passengerCount", b.status, b."approvedById", b."approvedAt", b."assignedDriverId", b."assignedVehicleId", b."assignedAt", b."returnedAt", b."createdAt", b."updatedAt", b."originalResourceId",
       u.name AS user_name, u."employeeId", dept.name AS department_name,
       r.name AS resource_name, r.type AS resource_type, r.status AS resource_status,
       ab.name AS approver_name,
       drv.id AS driver_id, du.name AS driver_name, drv."phoneNumber" AS driver_phone,
       v.id AS vehicle_id, v."plateNumber", v.brand, v.model, v.capacity,
       (
           SELECT EXISTS (
               SELECT 1 FROM bookings b2 
               WHERE b2.id != b.id 
                 AND b2.status = 'PENDING' 
                 AND b.status = 'PENDING'
                 AND b2."resourceId" = b."resourceId"
                 AND (
                     (b2."startDate" <= b."endDate" AND b2."endDate" >= b."startDate")
                 )
           )
       ) AS has_merge_suggestion,
       orig.name AS original_resource_name,
       orig.type AS original_resource_type,
       b."odometerStart", b."startLocation", b."startPhotoUrl"
FROM bookings b
JOIN users u ON u.id = b."userId"
JOIN departments dept ON dept.id = u."departmentId"
JOIN resources r ON r.id = b."resourceId"
LEFT JOIN resources orig ON orig.id = b."originalResourceId"
LEFT JOIN users ab ON ab.id = b."approvedById"
LEFT JOIN drivers drv ON drv.id = b."assignedDriverId"
LEFT JOIN users du ON du.id = drv."userId"
LEFT JOIN vehicles v ON v.id = b."assignedVehicleId"
WHERE b.id = $1 LIMIT 1
`

type GetBookingByIDRow struct {
	ID                 int32          `json:"id"`
	UserId             int32          `json:"userId"`
	ResourceId         int32          `json:"resourceId"`
	StartDate          time.Time      `json:"startDate"`
	EndDate            time.Time      `json:"endDate"`
	Purpose            string         `json:"purpose"`
	PassengerCount     int32          `json:"passengerCount"`
	Status             BookingStatus  `json:"status"`
	ApprovedById       sql.NullInt32  `json:"approvedById"`
	ApprovedAt         sql.NullTime   `json:"approvedAt"`
	AssignedDriverId   sql.NullInt32  `json:"assignedDriverId"`
	AssignedVehicleId  sql.NullInt32  `json:"assignedVehicleId"`
	AssignedAt         sql.NullTime   `json:"assignedAt"`
	ReturnedAt         sql.NullTime   `json:"returnedAt"`
	CreatedAt          time.Time      `json:"createdAt"`
	UpdatedAt          time.Time      `json:"updatedAt"`
	OriginalResourceId sql.NullInt32  `json:"originalResourceId"`
	UserName           string         `json:"user_name"`
	EmployeeId         string         `json:"employeeId"`
	DepartmentName     string         `json:"department_name"`
	ResourceName       string         `json:"resource_name"`
	ResourceType       ResourceType   `json:"resource_type"`
	ResourceStatus     ResourceStatus `json:"resource_status"`
	ApproverName       sql.NullString `json:"approver_name"`
	DriverID           sql.NullInt32  `json:"driver_id"`
	DriverName         sql.NullString `json:"driver_name"`
	DriverPhone        sql.NullString `json:"driver_phone"`
	VehicleID          sql.NullInt32  `json:"vehicle_id"`
	PlateNumber        sql.NullString `json:"plateNumber"`
	Brand              sql.NullString `json:"brand"`
	Model              sql.NullString `json:"model"`
	Capacity           sql.NullInt16  `json:"capacity"`
	HasMergeSuggestion   bool             `json:"has_merge_suggestion"`
	OriginalResourceName sql.NullString   `json:"original_resource_name"`
	OriginalResourceType NullResourceType `json:"original_resource_type"`
	OdometerStart        sql.NullInt32    `json:"odometerStart"`
	StartLocation        sql.NullString   `json:"startLocation"`
	StartPhotoUrl        sql.NullString   `json:"startPhotoUrl"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id int32) (GetBookingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
		&i.UserName,
		&i.EmployeeId,
		&i.DepartmentName,
		&i.ResourceName,
		&i.ResourceType,
		&i.ResourceStatus,
		&i.ApproverName,
		&i.DriverID,
		&i.DriverName,
		&i.DriverPhone,
		&i.VehicleID,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Capacity,
		&i.HasMergeSuggestion,
		&i.OriginalResourceName,
		&i.OriginalResourceType,
		&i.OdometerStart,
		&i.StartLocation,
		&i.StartPhotoUrl,
	)
	return i, err
}

const getDriverRatingByBooking = `-- name: GetDriverRatingByBooking :one
SELECT id, "bookingId", "driverId", "ratedById", rating, review, "createdAt" FROM driver_ratings WHERE "bookingId" = $1 LIMIT 1
`

func (q *Queries) GetDriverRatingByBooking(ctx context.Context, bookingid int32) (DriverRating, error) {
	row := q.db.QueryRowContext(ctx, getDriverRatingByBooking, bookingid)
	var i DriverRating
	err := row.Scan(
		&i.ID,
		&i.BookingId,
		&i.DriverId,
		&i.RatedById,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
	)
	return i, err
}

const getDriverRatings = `-- name: GetDriverRatings :many
SELECT dr.id, dr."bookingId", dr."driverId", dr."ratedById", dr.rating, dr.review, dr."createdAt", u.name AS rated_by_name
FROM driver_ratings dr
JOIN users u ON u.id = dr."ratedById"
WHERE dr."driverId" = $1
ORDER BY dr."createdAt" DESC
`

type GetDriverRatingsRow struct {
	ID          int32          `json:"id"`
	BookingId   int32          `json:"bookingId"`
	DriverId    int32          `json:"driverId"`
	RatedById   int32          `json:"ratedById"`
	Rating      int16          `json:"rating"`
	Review      sql.NullString `json:"review"`
	CreatedAt   time.Time      `json:"createdAt"`
	RatedByName string         `json:"rated_by_name"`
}

func (q *Queries) GetDriverRatings(ctx context.Context, driverid int32) ([]GetDriverRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDriverRatings, driverid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDriverRatingsRow
	for rows.Next() {
		var i GetDriverRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingId,
			&i.DriverId,
			&i.RatedById,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
			&i.RatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverlappingPassengerCount = `-- name: GetOverlappingPassengerCount :one
SELECT COALESCE(SUM("passengerCount"), 0)::int FROM bookings
WHERE "assignedVehicleId" = $1
  AND status IN ('APPROVED', 'ONGOING')
  AND "startDate" < $3
  AND "endDate" > $2
  AND id != $4
`

type GetOverlappingPassengerCountParams struct {
	AssignedVehicleId sql.NullInt32 `json:"assignedVehicleId"`
	EndDate           time.Time     `json:"endDate"`
	StartDate         time.Time     `json:"startDate"`
	ID                int32         `json:"id"`
}

func (q *Queries) GetOverlappingPassengerCount(ctx context.Context, arg GetOverlappingPassengerCountParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getOverlappingPassengerCount,
		arg.AssignedVehicleId,
		arg.EndDate,
		arg.StartDate,
		arg.ID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listBookings = `-- name: ListBookings :many
SELECT b.id, b."userId", b."resourceId", b."startDate", b."endDate", b.purpose, b."passengerCount", b.status, b."approvedById", b."approvedAt", b."assignedDriverId", b."assignedVehicleId", b."assignedAt", b."returnedAt", b."createdAt", b."updatedAt", b."originalResourceId",
       u.name AS user_name, u."employeeId", dept.name AS department_name,
       r.name AS resource_name, r.type AS resource_type, r.status AS resource_status,
       ab.name AS approver_name,
       drv.id AS driver_id, du.name AS driver_name, drv."phoneNumber" AS driver_phone,
       v.id AS vehicle_id, v."plateNumber", v.brand, v.model, v.capacity,
       (
           SELECT EXISTS (
               SELECT 1 FROM bookings b2 
               WHERE b2.id != b.id 
                 AND b2.status = 'PENDING' 
                 AND b.status = 'PENDING'
                 AND b2."resourceId" = b."resourceId"
                 AND (
                     (b2."startDate" <= b."endDate" AND b2."endDate" >= b."startDate")
                 )
           )
       ) AS has_merge_suggestion,
       orig.name AS original_resource_name,
       (SELECT bm."primaryBookingId" FROM booking_merges bm WHERE bm."mergedBookingId" = b.id LIMIT 1) AS merged_into_id,
       (SELECT COUNT(*) FROM booking_merges bm WHERE bm."primaryBookingId" = b.id) AS merge_count
FROM bookings b
JOIN users u ON u.id = b."userId"
JOIN departments dept ON dept.id = u."departmentId"
JOIN resources r ON r.id = b."resourceId"
LEFT JOIN resources orig ON orig.id = b."originalResourceId"
LEFT JOIN users ab ON ab.id = b."approvedById"
LEFT JOIN drivers drv ON drv.id = b."assignedDriverId"
LEFT JOIN users du ON du.id = drv."userId"
LEFT JOIN vehicles v ON v.id = b."assignedVehicleId"
WHERE ($3::int IS NULL OR b."userId" = $3::int)
  AND ($4::booking_status IS NULL OR b.status = $4::booking_status)
  AND ($5::int IS NULL OR b."resourceId" = $5::int)
  AND ($6::resource_type IS NULL OR r.type = $6::resource_type)
  AND ($7::int IS NULL OR b."assignedDriverId" = $7::int)
  AND ($8::timestamptz IS NULL OR b."startDate" >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR b."endDate" <= $9::timestamptz)
  AND ($10::text IS NULL OR r.name ILIKE '%' || $10::text || '%' OR u.name ILIKE '%' || $10::text || '%')
ORDER BY b."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListBookingsParams struct {
	Limit        int32             `json:"limit"`
	Offset       int32             `json:"offset"`
	UserID       sql.NullInt32     `json:"user_id"`
	Status       NullBookingStatus `json:"status"`
	ResourceID   sql.NullInt32     `json:"resource_id"`
	ResourceType NullResourceType  `json:"resource_type"`
	DriverID     sql.NullInt32     `json:"driver_id"`
	StartFrom    sql.NullTime      `json:"start_from"`
	EndTo        sql.NullTime      `json:"end_to"`
	Search       sql.NullString    `json:"search"`
}

type ListBookingsRow struct {
	ID                 int32          `json:"id"`
	UserId             int32          `json:"userId"`
	ResourceId         int32          `json:"resourceId"`
	StartDate          time.Time      `json:"startDate"`
	EndDate            time.Time      `json:"endDate"`
	Purpose            string         `json:"purpose"`
	PassengerCount     int32          `json:"passengerCount"`
	Status             BookingStatus  `json:"status"`
	ApprovedById       sql.NullInt32  `json:"approvedById"`
	ApprovedAt         sql.NullTime   `json:"approvedAt"`
	AssignedDriverId   sql.NullInt32  `json:"assignedDriverId"`
	AssignedVehicleId  sql.NullInt32  `json:"assignedVehicleId"`
	AssignedAt         sql.NullTime   `json:"assignedAt"`
	ReturnedAt         sql.NullTime   `json:"returnedAt"`
	CreatedAt          time.Time      `json:"createdAt"`
	UpdatedAt          time.Time      `json:"updatedAt"`
	OriginalResourceId sql.NullInt32  `json:"originalResourceId"`
	UserName           string         `json:"user_name"`
	EmployeeId         string         `json:"employeeId"`
	DepartmentName     string         `json:"department_name"`
	ResourceName       string         `json:"resource_name"`
	ResourceType       ResourceType   `json:"resource_type"`
	ResourceStatus     ResourceStatus `json:"resource_status"`
	ApproverName       sql.NullString `json:"approver_name"`
	DriverID           sql.NullInt32  `json:"driver_id"`
	DriverName         sql.NullString `json:"driver_name"`
	DriverPhone        sql.NullString `json:"driver_phone"`
	VehicleID          sql.NullInt32  `json:"vehicle_id"`
	PlateNumber        sql.NullString `json:"plateNumber"`
	Brand              sql.NullString `json:"brand"`
	Model              sql.NullString `json:"model"`
	Capacity           sql.NullInt16  `json:"capacity"`
	HasMergeSuggestion   bool           `json:"has_merge_suggestion"`
	OriginalResourceName sql.NullString `json:"original_resource_name"`
	MergedIntoId         sql.NullInt32  `json:"merged_into_id"`
	MergeCount           int64          `json:"merge_count"`
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookings,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Status,
		arg.ResourceID,
		arg.ResourceType,
		arg.DriverID,
		arg.StartFrom,
		arg.EndTo,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.ResourceId,
			&i.StartDate,
			&i.EndDate,
			&i.Purpose,
			&i.PassengerCount,
			&i.Status,
			&i.ApprovedById,
			&i.ApprovedAt,
			&i.AssignedDriverId,
			&i.AssignedVehicleId,
			&i.AssignedAt,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalResourceId,
			&i.UserName,
			&i.EmployeeId,
			&i.DepartmentName,
			&i.ResourceName,
			&i.ResourceType,
			&i.ResourceStatus,
			&i.ApproverName,
			&i.DriverID,
			&i.DriverName,
			&i.DriverPhone,
			&i.VehicleID,
			&i.PlateNumber,
			&i.Brand,
			&i.Model,
			&i.Capacity,
			&i.HasMergeSuggestion,
			&i.OriginalResourceName,
			&i.MergedIntoId,
			&i.MergeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredBookings = `-- name: MarkExpiredBookings :many
UPDATE bookings SET status = 'EXPIRED', "updatedAt" = NOW()
WHERE status = 'APPROVED' AND "endDate" < NOW()
RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

// Booking APPROVED tapi tidak pernah dimulai (tidak jadi ONGOING) selama masa bookingnya → EXPIRED
func (q *Queries) MarkExpiredBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, markExpiredBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.ResourceId,
			&i.StartDate,
			&i.EndDate,
			&i.Purpose,
			&i.PassengerCount,
			&i.Status,
			&i.ApprovedById,
			&i.ApprovedAt,
			&i.AssignedDriverId,
			&i.AssignedVehicleId,
			&i.AssignedAt,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalResourceId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIgnoredBookings = `-- name: MarkIgnoredBookings :many
UPDATE bookings SET status = 'IGNORED', "updatedAt" = NOW()
WHERE status = 'PENDING' AND "endDate" < NOW()
RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

// Booking PENDING tapi admin tidak merespons sampai masa bookingnya habis → IGNORED
func (q *Queries) MarkIgnoredBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, markIgnoredBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.ResourceId,
			&i.StartDate,
			&i.EndDate,
			&i.Purpose,
			&i.PassengerCount,
			&i.Status,
			&i.ApprovedById,
			&i.ApprovedAt,
			&i.AssignedDriverId,
			&i.AssignedVehicleId,
			&i.AssignedAt,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalResourceId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueBookings = `-- name: MarkOverdueBookings :many
UPDATE bookings SET status = 'OVERDUE', "updatedAt" = NOW()
WHERE status = 'ONGOING' AND "endDate" < NOW()
RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

// Booking ONGOING tapi lewat endDate → OVERDUE (sudah mulai tapi belum selesai tepat waktu)
func (q *Queries) MarkOverdueBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, markOverdueBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.ResourceId,
			&i.StartDate,
			&i.EndDate,
			&i.Purpose,
			&i.PassengerCount,
			&i.Status,
			&i.ApprovedById,
			&i.ApprovedAt,
			&i.AssignedDriverId,
			&i.AssignedVehicleId,
			&i.AssignedAt,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalResourceId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectBooking = `-- name: RejectBooking :one
UPDATE bookings
SET status = 'REJECTED', "approvedById" = $2, "approvedAt" = NOW(), "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

type RejectBookingParams struct {
	ID           int32         `json:"id"`
	ApprovedById sql.NullInt32 `json:"approvedById"`
}

func (q *Queries) RejectBooking(ctx context.Context, arg RejectBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, rejectBooking, arg.ID, arg.ApprovedById)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const startBooking = `-- name: StartBooking :one
UPDATE bookings SET status = 'ONGOING', "updatedAt" = NOW() WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

func (q *Queries) StartBooking(ctx context.Context, id int32) (Booking, error) {
	row := q.db.QueryRowContext(ctx, startBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const updateBookingResource = `-- name: UpdateBookingResource :one
UPDATE bookings SET "resourceId" = $2, "updatedAt" = NOW() WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

type UpdateBookingResourceParams struct {
	ID         int32 `json:"id"`
	ResourceId int32 `json:"resourceId"`
}

func (q *Queries) UpdateBookingResource(ctx context.Context, arg UpdateBookingResourceParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingResource, arg.ID, arg.ResourceId)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET status = $2, "updatedAt" = NOW() WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

type UpdateBookingStatusParams struct {
	ID     int32         `json:"id"`
	Status BookingStatus `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}

const updateMergedBooking = `-- name: UpdateMergedBooking :one
UPDATE bookings
SET "startDate" = $2, "endDate" = $3, "purpose" = $4,
    "assignedDriverId" = $5, "assignedVehicleId" = $6,
    "resourceId" = $7, "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "userId", "resourceId", "startDate", "endDate", purpose, "passengerCount", status, "approvedById", "approvedAt", "assignedDriverId", "assignedVehicleId", "assignedAt", "returnedAt", "createdAt", "updatedAt", "originalResourceId"
`

type UpdateMergedBookingParams struct {
	ID                int32         `json:"id"`
	StartDate         time.Time     `json:"startDate"`
	EndDate           time.Time     `json:"endDate"`
	Purpose           string        `json:"purpose"`
	AssignedDriverId  sql.NullInt32 `json:"assignedDriverId"`
	AssignedVehicleId sql.NullInt32 `json:"assignedVehicleId"`
	ResourceId        int32         `json:"resourceId"`
}

func (q *Queries) UpdateMergedBooking(ctx context.Context, arg UpdateMergedBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateMergedBooking,
		arg.ID,
		arg.StartDate,
		arg.EndDate,
		arg.Purpose,
		arg.AssignedDriverId,
		arg.AssignedVehicleId,
		arg.ResourceId,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.PassengerCount,
		&i.Status,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.AssignedDriverId,
		&i.AssignedVehicleId,
		&i.AssignedAt,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalResourceId,
	)
	return i, err
}
