// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package repository

import (
	"context"
)

const dashboardSummary = `-- name: DashboardSummary :one
SELECT
    (SELECT COUNT(*) FROM bookings) AS total_bookings,
    (SELECT COUNT(*) FROM rooms) AS total_rooms,
    (SELECT COUNT(*) FROM drivers) AS total_drivers,
    (SELECT COUNT(*) FROM vehicles) AS total_vehicles
`

type DashboardSummaryRow struct {
	TotalBookings int64 `json:"total_bookings"`
	TotalRooms    int64 `json:"total_rooms"`
	TotalDrivers  int64 `json:"total_drivers"`
	TotalVehicles int64 `json:"total_vehicles"`
}

func (q *Queries) DashboardSummary(ctx context.Context) (DashboardSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardSummary)
	var i DashboardSummaryRow
	err := row.Scan(
		&i.TotalBookings,
		&i.TotalRooms,
		&i.TotalDrivers,
		&i.TotalVehicles,
	)
	return i, err
}
