// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package repository

import (
	"context"
)

const dashboardSummary = `-- name: DashboardSummary :one
SELECT
    (SELECT COUNT(*) FROM bookings) AS total_bookings,
    (SELECT COUNT(*) FROM rooms) AS total_rooms,
    (SELECT COUNT(*) FROM rooms ro JOIN resources r ON r.id = ro."resourceId" WHERE r.status = 'AVAILABLE') AS available_rooms,
    (SELECT COUNT(*) FROM drivers WHERE "isActive" = TRUE) AS total_drivers,
    (SELECT COUNT(*) FROM drivers d WHERE d."isActive" = TRUE AND NOT EXISTS (
        SELECT 1 FROM bookings b WHERE b."assignedDriverId" = d.id AND b.status IN ('APPROVED', 'ONGOING')
    )) AS available_drivers,
    (SELECT COUNT(*) FROM vehicles) AS total_vehicles,
    (SELECT COUNT(*) FROM vehicles v JOIN resources r ON r.id = v."resourceId" WHERE r.status = 'AVAILABLE') AS available_vehicles
`

type DashboardSummaryRow struct {
	TotalBookings     int64 `json:"total_bookings"`
	TotalRooms        int64 `json:"total_rooms"`
	AvailableRooms    int64 `json:"available_rooms"`
	TotalDrivers      int64 `json:"total_drivers"`
	AvailableDrivers  int64 `json:"available_drivers"`
	TotalVehicles     int64 `json:"total_vehicles"`
	AvailableVehicles int64 `json:"available_vehicles"`
}

func (q *Queries) DashboardSummary(ctx context.Context) (DashboardSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardSummary)
	var i DashboardSummaryRow
	err := row.Scan(
		&i.TotalBookings,
		&i.TotalRooms,
		&i.AvailableRooms,
		&i.TotalDrivers,
		&i.AvailableDrivers,
		&i.TotalVehicles,
		&i.AvailableVehicles,
	)
	return i, err
}
