// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver_overtime.sql

package repository

import (
	"context"
	"time"
)

const createDriverOvertime = `-- name: CreateDriverOvertime :one
INSERT INTO driver_overtimes (
    "bookingId", "driverId", "scheduledEndAt", "actualEndAt", "overtimeMinutes"
) VALUES ($1, $2, $3, $4, $5) RETURNING id, "bookingId", "driverId", "scheduledEndAt", "actualEndAt", "overtimeMinutes", "createdAt"
`

type CreateDriverOvertimeParams struct {
	BookingId       int32     `json:"bookingId"`
	DriverId        int32     `json:"driverId"`
	ScheduledEndAt  time.Time `json:"scheduledEndAt"`
	ActualEndAt     time.Time `json:"actualEndAt"`
	OvertimeMinutes int32     `json:"overtimeMinutes"`
}

func (q *Queries) CreateDriverOvertime(ctx context.Context, arg CreateDriverOvertimeParams) (DriverOvertime, error) {
	row := q.db.QueryRowContext(ctx, createDriverOvertime,
		arg.BookingId,
		arg.DriverId,
		arg.ScheduledEndAt,
		arg.ActualEndAt,
		arg.OvertimeMinutes,
	)
	var i DriverOvertime
	err := row.Scan(
		&i.ID,
		&i.BookingId,
		&i.DriverId,
		&i.ScheduledEndAt,
		&i.ActualEndAt,
		&i.OvertimeMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const getOvertimeByBooking = `-- name: GetOvertimeByBooking :one
SELECT id, "bookingId", "driverId", "scheduledEndAt", "actualEndAt", "overtimeMinutes", "createdAt" FROM driver_overtimes WHERE "bookingId" = $1 LIMIT 1
`

func (q *Queries) GetOvertimeByBooking(ctx context.Context, bookingid int32) (DriverOvertime, error) {
	row := q.db.QueryRowContext(ctx, getOvertimeByBooking, bookingid)
	var i DriverOvertime
	err := row.Scan(
		&i.ID,
		&i.BookingId,
		&i.DriverId,
		&i.ScheduledEndAt,
		&i.ActualEndAt,
		&i.OvertimeMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const listOvertimeByDriver = `-- name: ListOvertimeByDriver :many
SELECT ot.id, ot."bookingId", ot."driverId", ot."scheduledEndAt", ot."actualEndAt", ot."overtimeMinutes", ot."createdAt", b.purpose, b."startDate", b."endDate" AS "bookingEndDate"
FROM driver_overtimes ot
JOIN bookings b ON b.id = ot."bookingId"
WHERE ot."driverId" = $1
ORDER BY ot."createdAt" DESC
`

type ListOvertimeByDriverRow struct {
	ID              int32     `json:"id"`
	BookingId       int32     `json:"bookingId"`
	DriverId        int32     `json:"driverId"`
	ScheduledEndAt  time.Time `json:"scheduledEndAt"`
	ActualEndAt     time.Time `json:"actualEndAt"`
	OvertimeMinutes int32     `json:"overtimeMinutes"`
	CreatedAt       time.Time `json:"createdAt"`
	Purpose         string    `json:"purpose"`
	StartDate       time.Time `json:"startDate"`
	BookingEndDate  time.Time `json:"bookingEndDate"`
}

func (q *Queries) ListOvertimeByDriver(ctx context.Context, driverid int32) ([]ListOvertimeByDriverRow, error) {
	rows, err := q.db.QueryContext(ctx, listOvertimeByDriver, driverid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOvertimeByDriverRow
	for rows.Next() {
		var i ListOvertimeByDriverRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingId,
			&i.DriverId,
			&i.ScheduledEndAt,
			&i.ActualEndAt,
			&i.OvertimeMinutes,
			&i.CreatedAt,
			&i.Purpose,
			&i.StartDate,
			&i.BookingEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
