// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const assignDriverToVehicle = `-- name: AssignDriverToVehicle :one
INSERT INTO driver_assignments ("driverId", "vehicleId") VALUES ($1, $2) RETURNING id, "driverId", "vehicleId", "assignedAt", "releasedAt"
`

type AssignDriverToVehicleParams struct {
	DriverId  int32 `json:"driverId"`
	VehicleId int32 `json:"vehicleId"`
}

func (q *Queries) AssignDriverToVehicle(ctx context.Context, arg AssignDriverToVehicleParams) (DriverAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignDriverToVehicle, arg.DriverId, arg.VehicleId)
	var i DriverAssignment
	err := row.Scan(
		&i.ID,
		&i.DriverId,
		&i.VehicleId,
		&i.AssignedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const countDrivers = `-- name: CountDrivers :one
SELECT COUNT(*) FROM drivers d
WHERE ($1::boolean IS NULL OR d."isActive" = $1::boolean)
`

func (q *Queries) CountDrivers(ctx context.Context, isActive sql.NullBool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDrivers, isActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers ("userId", "licenseNumber", "phoneNumber", "isActive")
VALUES ($1, $2, $3, TRUE) RETURNING id, "userId", "licenseNumber", "phoneNumber", "isActive", "createdAt"
`

type CreateDriverParams struct {
	UserId        int32  `json:"userId"`
	LicenseNumber string `json:"licenseNumber"`
	PhoneNumber   string `json:"phoneNumber"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, createDriver, arg.UserId, arg.LicenseNumber, arg.PhoneNumber)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.LicenseNumber,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDriverAssignmentHistory = `-- name: GetDriverAssignmentHistory :many
SELECT da.id, da."driverId", da."vehicleId", da."assignedAt", da."releasedAt", v."plateNumber", v.brand, v.model
FROM driver_assignments da
JOIN vehicles v ON v.id = da."vehicleId"
WHERE da."driverId" = $1
ORDER BY da."assignedAt" DESC
`

type GetDriverAssignmentHistoryRow struct {
	ID          int32        `json:"id"`
	DriverId    int32        `json:"driverId"`
	VehicleId   int32        `json:"vehicleId"`
	AssignedAt  time.Time    `json:"assignedAt"`
	ReleasedAt  sql.NullTime `json:"releasedAt"`
	PlateNumber string       `json:"plateNumber"`
	Brand       string       `json:"brand"`
	Model       string       `json:"model"`
}

func (q *Queries) GetDriverAssignmentHistory(ctx context.Context, driverid int32) ([]GetDriverAssignmentHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getDriverAssignmentHistory, driverid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDriverAssignmentHistoryRow
	for rows.Next() {
		var i GetDriverAssignmentHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverId,
			&i.VehicleId,
			&i.AssignedAt,
			&i.ReleasedAt,
			&i.PlateNumber,
			&i.Brand,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriverByID = `-- name: GetDriverByID :one
SELECT d.id, d."userId", d."licenseNumber", d."phoneNumber", d."isActive", d."createdAt", u.name AS user_name, u."employeeId", u.email, u."profilePhoto",
       v."plateNumber" AS assigned_plate
FROM drivers d
JOIN users u ON u.id = d."userId"
LEFT JOIN driver_assignments da ON da."driverId" = d.id AND da."releasedAt" IS NULL
LEFT JOIN vehicles v ON v.id = da."vehicleId"
WHERE d.id = $1 LIMIT 1
`

type GetDriverByIDRow struct {
	ID            int32          `json:"id"`
	UserId        int32          `json:"userId"`
	LicenseNumber string         `json:"licenseNumber"`
	PhoneNumber   string         `json:"phoneNumber"`
	IsActive      bool           `json:"isActive"`
	CreatedAt     time.Time      `json:"createdAt"`
	UserName      string         `json:"user_name"`
	EmployeeId    string         `json:"employeeId"`
	Email         string         `json:"email"`
	ProfilePhoto  sql.NullString `json:"profilePhoto"`
	AssignedPlate sql.NullString `json:"assigned_plate"`
}

func (q *Queries) GetDriverByID(ctx context.Context, id int32) (GetDriverByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDriverByID, id)
	var i GetDriverByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.LicenseNumber,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserName,
		&i.EmployeeId,
		&i.Email,
		&i.ProfilePhoto,
		&i.AssignedPlate,
	)
	return i, err
}

const getDriverByUserID = `-- name: GetDriverByUserID :one
SELECT id, "userId", "licenseNumber", "phoneNumber", "isActive", "createdAt" FROM drivers WHERE "userId" = $1 LIMIT 1
`

func (q *Queries) GetDriverByUserID(ctx context.Context, userid int32) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriverByUserID, userid)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.LicenseNumber,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDriverCurrentAssignment = `-- name: GetDriverCurrentAssignment :one
SELECT da.id, da."driverId", da."vehicleId", da."assignedAt", da."releasedAt", v."plateNumber", v.brand, v.model
FROM driver_assignments da
JOIN vehicles v ON v.id = da."vehicleId"
WHERE da."driverId" = $1 AND da."releasedAt" IS NULL LIMIT 1
`

type GetDriverCurrentAssignmentRow struct {
	ID          int32        `json:"id"`
	DriverId    int32        `json:"driverId"`
	VehicleId   int32        `json:"vehicleId"`
	AssignedAt  time.Time    `json:"assignedAt"`
	ReleasedAt  sql.NullTime `json:"releasedAt"`
	PlateNumber string       `json:"plateNumber"`
	Brand       string       `json:"brand"`
	Model       string       `json:"model"`
}

func (q *Queries) GetDriverCurrentAssignment(ctx context.Context, driverid int32) (GetDriverCurrentAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getDriverCurrentAssignment, driverid)
	var i GetDriverCurrentAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.DriverId,
		&i.VehicleId,
		&i.AssignedAt,
		&i.ReleasedAt,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
	)
	return i, err
}

const listAvailableDrivers = `-- name: ListAvailableDrivers :many
SELECT d.id AS driver_id, u.name AS driver_name, u."employeeId",
       v.id AS vehicle_id, v."plateNumber", v.capacity,
       COALESCE(
           (SELECT SUM(b."passengerCount")::int
            FROM bookings b
            WHERE b."assignedDriverId" = d.id
              AND b.status IN ('APPROVED', 'ONGOING')
              AND b."startDate" < $1::timestamptz
              AND b."endDate" > $2::timestamptz
           ), 0
       )::int AS overlapping_passengers,
       (SELECT b.purpose
        FROM bookings b
        WHERE b."assignedDriverId" = d.id
          AND b.status IN ('APPROVED', 'ONGOING')
          AND b."startDate" < $1::timestamptz
          AND b."endDate" > $2::timestamptz
        ORDER BY b."startDate" ASC LIMIT 1) AS overlapping_purpose
FROM drivers d
JOIN users u ON u.id = d."userId"
LEFT JOIN driver_assignments da ON da."driverId" = d.id AND da."releasedAt" IS NULL
LEFT JOIN vehicles v ON v.id = da."vehicleId"
WHERE d."isActive" = TRUE
ORDER BY overlapping_passengers ASC
`

type ListAvailableDriversParams struct {
	EndTo     time.Time `json:"end_to"`
	StartFrom time.Time `json:"start_from"`
}

type ListAvailableDriversRow struct {
	DriverID              int32          `json:"driver_id"`
	DriverName            string         `json:"driver_name"`
	EmployeeId            string         `json:"employeeId"`
	VehicleID             sql.NullInt32  `json:"vehicle_id"`
	PlateNumber           sql.NullString `json:"plateNumber"`
	Capacity              sql.NullInt16  `json:"capacity"`
	OverlappingPassengers int32          `json:"overlapping_passengers"`
	OverlappingPurpose    sql.NullString `json:"overlapping_purpose"`
}

func (q *Queries) ListAvailableDrivers(ctx context.Context, arg ListAvailableDriversParams) ([]ListAvailableDriversRow, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableDrivers, arg.EndTo, arg.StartFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableDriversRow
	for rows.Next() {
		var i ListAvailableDriversRow
		if err := rows.Scan(
			&i.DriverID,
			&i.DriverName,
			&i.EmployeeId,
			&i.VehicleID,
			&i.PlateNumber,
			&i.Capacity,
			&i.OverlappingPassengers,
			&i.OverlappingPurpose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrivers = `-- name: ListDrivers :many
SELECT d.id, d."userId", d."licenseNumber", d."phoneNumber", d."isActive", d."createdAt", u.name AS user_name, u."employeeId", u.email,
       v."plateNumber" AS assigned_plate
FROM drivers d
JOIN users u ON u.id = d."userId"
LEFT JOIN driver_assignments da ON da."driverId" = d.id AND da."releasedAt" IS NULL
LEFT JOIN vehicles v ON v.id = da."vehicleId"
WHERE ($3::boolean IS NULL OR d."isActive" = $3::boolean)
ORDER BY d."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListDriversParams struct {
	Limit    int32        `json:"limit"`
	Offset   int32        `json:"offset"`
	IsActive sql.NullBool `json:"is_active"`
}

type ListDriversRow struct {
	ID            int32          `json:"id"`
	UserId        int32          `json:"userId"`
	LicenseNumber string         `json:"licenseNumber"`
	PhoneNumber   string         `json:"phoneNumber"`
	IsActive      bool           `json:"isActive"`
	CreatedAt     time.Time      `json:"createdAt"`
	UserName      string         `json:"user_name"`
	EmployeeId    string         `json:"employeeId"`
	Email         string         `json:"email"`
	AssignedPlate sql.NullString `json:"assigned_plate"`
}

func (q *Queries) ListDrivers(ctx context.Context, arg ListDriversParams) ([]ListDriversRow, error) {
	rows, err := q.db.QueryContext(ctx, listDrivers, arg.Limit, arg.Offset, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriversRow
	for rows.Next() {
		var i ListDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.LicenseNumber,
			&i.PhoneNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UserName,
			&i.EmployeeId,
			&i.Email,
			&i.AssignedPlate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDriver = `-- name: ReleaseDriver :exec
UPDATE driver_assignments SET "releasedAt" = NOW()
WHERE "driverId" = $1 AND "releasedAt" IS NULL
`

func (q *Queries) ReleaseDriver(ctx context.Context, driverid int32) error {
	_, err := q.db.ExecContext(ctx, releaseDriver, driverid)
	return err
}

const toggleDriverActive = `-- name: ToggleDriverActive :one
UPDATE drivers SET "isActive" = NOT "isActive" WHERE id = $1 RETURNING id, "userId", "licenseNumber", "phoneNumber", "isActive", "createdAt"
`

func (q *Queries) ToggleDriverActive(ctx context.Context, id int32) (Driver, error) {
	row := q.db.QueryRowContext(ctx, toggleDriverActive, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.LicenseNumber,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE drivers SET "licenseNumber" = $2, "phoneNumber" = $3 WHERE id = $1 RETURNING id, "userId", "licenseNumber", "phoneNumber", "isActive", "createdAt"
`

type UpdateDriverParams struct {
	ID            int32  `json:"id"`
	LicenseNumber string `json:"licenseNumber"`
	PhoneNumber   string `json:"phoneNumber"`
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, updateDriver, arg.ID, arg.LicenseNumber, arg.PhoneNumber)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.LicenseNumber,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
