// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuel_expense.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const countFuelExpenses = `-- name: CountFuelExpenses :one
SELECT COUNT(*) FROM fuel_expenses fe
WHERE ($1::int IS NULL OR fe."driverId" = $1::int)
  AND ($2::int IS NULL OR fe."vehicleId" = $2::int)
  AND ($3::fuel_type IS NULL OR fe."fuelType" = $3::fuel_type)
`

type CountFuelExpensesParams struct {
	DriverID  sql.NullInt32 `json:"driver_id"`
	VehicleID sql.NullInt32 `json:"vehicle_id"`
	FuelType  NullFuelType  `json:"fuel_type"`
}

func (q *Queries) CountFuelExpenses(ctx context.Context, arg CountFuelExpensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFuelExpenses, arg.DriverID, arg.VehicleID, arg.FuelType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFuelExpenseBBM = `-- name: CreateFuelExpenseBBM :one
INSERT INTO fuel_expenses (
    "driverId", "vehicleId", "bookingId", "fuelType",
    liter, "pricePerLiter", "odometerBefore", "odometerAfter",
    "totalAmount", note
) VALUES ($1, $2, $3, 'BBM', $4, $5, $6, $7, $8, $9) RETURNING id, "driverId", "vehicleId", "bookingId", "fuelType", liter, "pricePerLiter", "odometerBefore", "odometerAfter", kwh, "pricePerKwh", "batteryBefore", "batteryAfter", "totalAmount", note, "createdAt"
`

type CreateFuelExpenseBBMParams struct {
	DriverId       int32          `json:"driverId"`
	VehicleId      int32          `json:"vehicleId"`
	BookingId      sql.NullInt32  `json:"bookingId"`
	Liter          sql.NullString `json:"liter"`
	PricePerLiter  sql.NullString `json:"pricePerLiter"`
	OdometerBefore sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter  sql.NullInt32  `json:"odometerAfter"`
	TotalAmount    string         `json:"totalAmount"`
	Note           sql.NullString `json:"note"`
}

func (q *Queries) CreateFuelExpenseBBM(ctx context.Context, arg CreateFuelExpenseBBMParams) (FuelExpense, error) {
	row := q.db.QueryRowContext(ctx, createFuelExpenseBBM,
		arg.DriverId,
		arg.VehicleId,
		arg.BookingId,
		arg.Liter,
		arg.PricePerLiter,
		arg.OdometerBefore,
		arg.OdometerAfter,
		arg.TotalAmount,
		arg.Note,
	)
	var i FuelExpense
	err := row.Scan(
		&i.ID,
		&i.DriverId,
		&i.VehicleId,
		&i.BookingId,
		&i.FuelType,
		&i.Liter,
		&i.PricePerLiter,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.Kwh,
		&i.PricePerKwh,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createFuelExpenseListrik = `-- name: CreateFuelExpenseListrik :one
INSERT INTO fuel_expenses (
    "driverId", "vehicleId", "bookingId", "fuelType",
    kwh, "pricePerKwh", "batteryBefore", "batteryAfter",
    "totalAmount", note
) VALUES ($1, $2, $3, 'LISTRIK', $4, $5, $6, $7, $8, $9) RETURNING id, "driverId", "vehicleId", "bookingId", "fuelType", liter, "pricePerLiter", "odometerBefore", "odometerAfter", kwh, "pricePerKwh", "batteryBefore", "batteryAfter", "totalAmount", note, "createdAt"
`

type CreateFuelExpenseListrikParams struct {
	DriverId      int32          `json:"driverId"`
	VehicleId     int32          `json:"vehicleId"`
	BookingId     sql.NullInt32  `json:"bookingId"`
	Kwh           sql.NullString `json:"kwh"`
	PricePerKwh   sql.NullString `json:"pricePerKwh"`
	BatteryBefore sql.NullString `json:"batteryBefore"`
	BatteryAfter  sql.NullString `json:"batteryAfter"`
	TotalAmount   string         `json:"totalAmount"`
	Note          sql.NullString `json:"note"`
}

func (q *Queries) CreateFuelExpenseListrik(ctx context.Context, arg CreateFuelExpenseListrikParams) (FuelExpense, error) {
	row := q.db.QueryRowContext(ctx, createFuelExpenseListrik,
		arg.DriverId,
		arg.VehicleId,
		arg.BookingId,
		arg.Kwh,
		arg.PricePerKwh,
		arg.BatteryBefore,
		arg.BatteryAfter,
		arg.TotalAmount,
		arg.Note,
	)
	var i FuelExpense
	err := row.Scan(
		&i.ID,
		&i.DriverId,
		&i.VehicleId,
		&i.BookingId,
		&i.FuelType,
		&i.Liter,
		&i.PricePerLiter,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.Kwh,
		&i.PricePerKwh,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFuelExpense = `-- name: DeleteFuelExpense :exec
DELETE FROM fuel_expenses WHERE id = $1
`

func (q *Queries) DeleteFuelExpense(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFuelExpense, id)
	return err
}

const getFuelExpenseByID = `-- name: GetFuelExpenseByID :one
SELECT fe.id, fe."driverId", fe."vehicleId", fe."bookingId", fe."fuelType", fe.liter, fe."pricePerLiter", fe."odometerBefore", fe."odometerAfter", fe.kwh, fe."pricePerKwh", fe."batteryBefore", fe."batteryAfter", fe."totalAmount", fe.note, fe."createdAt", d_u.name AS driver_name, v."plateNumber", r.name AS vehicle_name
FROM fuel_expenses fe
JOIN drivers d ON d.id = fe."driverId"
JOIN users d_u ON d_u.id = d."userId"
JOIN vehicles v ON v.id = fe."vehicleId"
JOIN resources r ON r.id = v."resourceId"
WHERE fe.id = $1 LIMIT 1
`

type GetFuelExpenseByIDRow struct {
	ID             int32          `json:"id"`
	DriverId       int32          `json:"driverId"`
	VehicleId      int32          `json:"vehicleId"`
	BookingId      sql.NullInt32  `json:"bookingId"`
	FuelType       FuelType       `json:"fuelType"`
	Liter          sql.NullString `json:"liter"`
	PricePerLiter  sql.NullString `json:"pricePerLiter"`
	OdometerBefore sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter  sql.NullInt32  `json:"odometerAfter"`
	Kwh            sql.NullString `json:"kwh"`
	PricePerKwh    sql.NullString `json:"pricePerKwh"`
	BatteryBefore  sql.NullString `json:"batteryBefore"`
	BatteryAfter   sql.NullString `json:"batteryAfter"`
	TotalAmount    string         `json:"totalAmount"`
	Note           sql.NullString `json:"note"`
	CreatedAt      time.Time      `json:"createdAt"`
	DriverName     string         `json:"driver_name"`
	PlateNumber    string         `json:"plateNumber"`
	VehicleName    string         `json:"vehicle_name"`
}

func (q *Queries) GetFuelExpenseByID(ctx context.Context, id int32) (GetFuelExpenseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFuelExpenseByID, id)
	var i GetFuelExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.DriverId,
		&i.VehicleId,
		&i.BookingId,
		&i.FuelType,
		&i.Liter,
		&i.PricePerLiter,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.Kwh,
		&i.PricePerKwh,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.DriverName,
		&i.PlateNumber,
		&i.VehicleName,
	)
	return i, err
}

const listFuelExpenses = `-- name: ListFuelExpenses :many
SELECT fe.id, fe."driverId", fe."vehicleId", fe."bookingId", fe."fuelType", fe.liter, fe."pricePerLiter", fe."odometerBefore", fe."odometerAfter", fe.kwh, fe."pricePerKwh", fe."batteryBefore", fe."batteryAfter", fe."totalAmount", fe.note, fe."createdAt", d_u.name AS driver_name, v."plateNumber", r.name AS vehicle_name
FROM fuel_expenses fe
JOIN drivers d ON d.id = fe."driverId"
JOIN users d_u ON d_u.id = d."userId"
JOIN vehicles v ON v.id = fe."vehicleId"
JOIN resources r ON r.id = v."resourceId"
WHERE ($3::int IS NULL OR fe."driverId" = $3::int)
  AND ($4::int IS NULL OR fe."vehicleId" = $4::int)
  AND ($5::fuel_type IS NULL OR fe."fuelType" = $5::fuel_type)
ORDER BY fe."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListFuelExpensesParams struct {
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
	DriverID  sql.NullInt32 `json:"driver_id"`
	VehicleID sql.NullInt32 `json:"vehicle_id"`
	FuelType  NullFuelType  `json:"fuel_type"`
}

type ListFuelExpensesRow struct {
	ID             int32          `json:"id"`
	DriverId       int32          `json:"driverId"`
	VehicleId      int32          `json:"vehicleId"`
	BookingId      sql.NullInt32  `json:"bookingId"`
	FuelType       FuelType       `json:"fuelType"`
	Liter          sql.NullString `json:"liter"`
	PricePerLiter  sql.NullString `json:"pricePerLiter"`
	OdometerBefore sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter  sql.NullInt32  `json:"odometerAfter"`
	Kwh            sql.NullString `json:"kwh"`
	PricePerKwh    sql.NullString `json:"pricePerKwh"`
	BatteryBefore  sql.NullString `json:"batteryBefore"`
	BatteryAfter   sql.NullString `json:"batteryAfter"`
	TotalAmount    string         `json:"totalAmount"`
	Note           sql.NullString `json:"note"`
	CreatedAt      time.Time      `json:"createdAt"`
	DriverName     string         `json:"driver_name"`
	PlateNumber    string         `json:"plateNumber"`
	VehicleName    string         `json:"vehicle_name"`
}

func (q *Queries) ListFuelExpenses(ctx context.Context, arg ListFuelExpensesParams) ([]ListFuelExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFuelExpenses,
		arg.Limit,
		arg.Offset,
		arg.DriverID,
		arg.VehicleID,
		arg.FuelType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFuelExpensesRow
	for rows.Next() {
		var i ListFuelExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.DriverId,
			&i.VehicleId,
			&i.BookingId,
			&i.FuelType,
			&i.Liter,
			&i.PricePerLiter,
			&i.OdometerBefore,
			&i.OdometerAfter,
			&i.Kwh,
			&i.PricePerKwh,
			&i.BatteryBefore,
			&i.BatteryAfter,
			&i.TotalAmount,
			&i.Note,
			&i.CreatedAt,
			&i.DriverName,
			&i.PlateNumber,
			&i.VehicleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFuelExpenseBBM = `-- name: UpdateFuelExpenseBBM :one
UPDATE fuel_expenses
SET liter = $2, "pricePerLiter" = $3, "odometerBefore" = $4,
    "odometerAfter" = $5, "totalAmount" = $6, note = $7
WHERE id = $1 RETURNING id, "driverId", "vehicleId", "bookingId", "fuelType", liter, "pricePerLiter", "odometerBefore", "odometerAfter", kwh, "pricePerKwh", "batteryBefore", "batteryAfter", "totalAmount", note, "createdAt"
`

type UpdateFuelExpenseBBMParams struct {
	ID             int32          `json:"id"`
	Liter          sql.NullString `json:"liter"`
	PricePerLiter  sql.NullString `json:"pricePerLiter"`
	OdometerBefore sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter  sql.NullInt32  `json:"odometerAfter"`
	TotalAmount    string         `json:"totalAmount"`
	Note           sql.NullString `json:"note"`
}

func (q *Queries) UpdateFuelExpenseBBM(ctx context.Context, arg UpdateFuelExpenseBBMParams) (FuelExpense, error) {
	row := q.db.QueryRowContext(ctx, updateFuelExpenseBBM,
		arg.ID,
		arg.Liter,
		arg.PricePerLiter,
		arg.OdometerBefore,
		arg.OdometerAfter,
		arg.TotalAmount,
		arg.Note,
	)
	var i FuelExpense
	err := row.Scan(
		&i.ID,
		&i.DriverId,
		&i.VehicleId,
		&i.BookingId,
		&i.FuelType,
		&i.Liter,
		&i.PricePerLiter,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.Kwh,
		&i.PricePerKwh,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const updateFuelExpenseListrik = `-- name: UpdateFuelExpenseListrik :one
UPDATE fuel_expenses
SET kwh = $2, "pricePerKwh" = $3, "batteryBefore" = $4,
    "batteryAfter" = $5, "totalAmount" = $6, note = $7
WHERE id = $1 RETURNING id, "driverId", "vehicleId", "bookingId", "fuelType", liter, "pricePerLiter", "odometerBefore", "odometerAfter", kwh, "pricePerKwh", "batteryBefore", "batteryAfter", "totalAmount", note, "createdAt"
`

type UpdateFuelExpenseListrikParams struct {
	ID            int32          `json:"id"`
	Kwh           sql.NullString `json:"kwh"`
	PricePerKwh   sql.NullString `json:"pricePerKwh"`
	BatteryBefore sql.NullString `json:"batteryBefore"`
	BatteryAfter  sql.NullString `json:"batteryAfter"`
	TotalAmount   string         `json:"totalAmount"`
	Note          sql.NullString `json:"note"`
}

func (q *Queries) UpdateFuelExpenseListrik(ctx context.Context, arg UpdateFuelExpenseListrikParams) (FuelExpense, error) {
	row := q.db.QueryRowContext(ctx, updateFuelExpenseListrik,
		arg.ID,
		arg.Kwh,
		arg.PricePerKwh,
		arg.BatteryBefore,
		arg.BatteryAfter,
		arg.TotalAmount,
		arg.Note,
	)
	var i FuelExpense
	err := row.Scan(
		&i.ID,
		&i.DriverId,
		&i.VehicleId,
		&i.BookingId,
		&i.FuelType,
		&i.Liter,
		&i.PricePerLiter,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.Kwh,
		&i.PricePerKwh,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
