// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuel_expense.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const countFuelExpenses = `-- name: CountFuelExpenses :one
SELECT COUNT(*) FROM fuel_expenses fe
JOIN fuel_types ft ON ft.id = fe."fuelTypeId"
WHERE ($1::int IS NULL OR fe."driverId" = $1::int)
  AND ($2::int IS NULL OR fe."vehicleId" = $2::int)
  AND ($3::fuel_category IS NULL OR ft.type = $3::fuel_category)
`

type CountFuelExpensesParams struct {
	DriverID     sql.NullInt32    `json:"driver_id"`
	VehicleID    sql.NullInt32    `json:"vehicle_id"`
	FuelCategory NullFuelCategory `json:"fuel_category"`
}

func (q *Queries) CountFuelExpenses(ctx context.Context, arg CountFuelExpensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFuelExpenses, arg.DriverID, arg.VehicleID, arg.FuelCategory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFuelExpense = `-- name: CreateFuelExpense :one
INSERT INTO fuel_expenses (
    "vehicleId", "fuelTypeId", "bookingId", "driverId", "recordedById",
    "fuelGrade", "proofPhotoUrl", "odometerBefore", "odometerAfter", "distanceKm",
    quantity, "pricePerUnit", "totalCost",
    "batteryBefore", "batteryAfter", location, "stationName", note
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING id, "vehicleId", "fuelTypeId", "bookingId", "driverId", "recordedById", "fuelGrade", "proofPhotoUrl", "odometerBefore", "odometerAfter", "distanceKm", quantity, "pricePerUnit", "totalCost", "batteryBefore", "batteryAfter", location, "stationName", note, "createdAt"
`

type CreateFuelExpenseParams struct {
	VehicleId      int32          `json:"vehicleId"`
	FuelTypeId     int32          `json:"fuelTypeId"`
	BookingId      sql.NullInt32  `json:"bookingId"`
	DriverId       sql.NullInt32  `json:"driverId"`
	RecordedById   int32          `json:"recordedById"`
	FuelGrade      sql.NullString `json:"fuelGrade"`
	ProofPhotoUrl  sql.NullString `json:"proofPhotoUrl"`
	OdometerBefore sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter  sql.NullInt32  `json:"odometerAfter"`
	DistanceKm     sql.NullInt32  `json:"distanceKm"`
	Quantity       sql.NullString `json:"quantity"`
	PricePerUnit   sql.NullString `json:"pricePerUnit"`
	TotalCost      sql.NullString `json:"totalCost"`
	BatteryBefore  sql.NullString `json:"batteryBefore"`
	BatteryAfter   sql.NullString `json:"batteryAfter"`
	Location       string         `json:"location"`
	StationName    sql.NullString `json:"stationName"`
	Note           sql.NullString `json:"note"`
}

func (q *Queries) CreateFuelExpense(ctx context.Context, arg CreateFuelExpenseParams) (FuelExpense, error) {
	row := q.db.QueryRowContext(ctx, createFuelExpense,
		arg.VehicleId,
		arg.FuelTypeId,
		arg.BookingId,
		arg.DriverId,
		arg.RecordedById,
		arg.FuelGrade,
		arg.ProofPhotoUrl,
		arg.OdometerBefore,
		arg.OdometerAfter,
		arg.DistanceKm,
		arg.Quantity,
		arg.PricePerUnit,
		arg.TotalCost,
		arg.BatteryBefore,
		arg.BatteryAfter,
		arg.Location,
		arg.StationName,
		arg.Note,
	)
	var i FuelExpense
	err := row.Scan(
		&i.ID,
		&i.VehicleId,
		&i.FuelTypeId,
		&i.BookingId,
		&i.DriverId,
		&i.RecordedById,
		&i.FuelGrade,
		&i.ProofPhotoUrl,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.DistanceKm,
		&i.Quantity,
		&i.PricePerUnit,
		&i.TotalCost,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.Location,
		&i.StationName,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFuelExpense = `-- name: DeleteFuelExpense :exec
DELETE FROM fuel_expenses WHERE id = $1
`

func (q *Queries) DeleteFuelExpense(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFuelExpense, id)
	return err
}

const getFuelExpenseByID = `-- name: GetFuelExpenseByID :one
SELECT fe.id, fe."vehicleId", fe."fuelTypeId", fe."bookingId", fe."driverId", fe."recordedById", fe."fuelGrade", fe."proofPhotoUrl", fe."odometerBefore", fe."odometerAfter", fe."distanceKm", fe.quantity, fe."pricePerUnit", fe."totalCost", fe."batteryBefore", fe."batteryAfter", fe.location, fe."stationName", fe.note, fe."createdAt", d_u.name AS driver_name, v."plateNumber", r.name AS vehicle_name, ft.type AS fuel_category_name
FROM fuel_expenses fe
LEFT JOIN drivers d ON d.id = fe."driverId"
LEFT JOIN users d_u ON d_u.id = d."userId"
JOIN vehicles v ON v.id = fe."vehicleId"
JOIN resources r ON r.id = v."resourceId"
JOIN fuel_types ft ON ft.id = fe."fuelTypeId"
WHERE fe.id = $1 LIMIT 1
`

type GetFuelExpenseByIDRow struct {
	ID               int32          `json:"id"`
	VehicleId        int32          `json:"vehicleId"`
	FuelTypeId       int32          `json:"fuelTypeId"`
	BookingId        sql.NullInt32  `json:"bookingId"`
	DriverId         sql.NullInt32  `json:"driverId"`
	RecordedById     int32          `json:"recordedById"`
	FuelGrade        sql.NullString `json:"fuelGrade"`
	ProofPhotoUrl    sql.NullString `json:"proofPhotoUrl"`
	OdometerBefore   sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter    sql.NullInt32  `json:"odometerAfter"`
	DistanceKm       sql.NullInt32  `json:"distanceKm"`
	Quantity         sql.NullString `json:"quantity"`
	PricePerUnit     sql.NullString `json:"pricePerUnit"`
	TotalCost        sql.NullString `json:"totalCost"`
	BatteryBefore    sql.NullString `json:"batteryBefore"`
	BatteryAfter     sql.NullString `json:"batteryAfter"`
	Location         string         `json:"location"`
	StationName      sql.NullString `json:"stationName"`
	Note             sql.NullString `json:"note"`
	CreatedAt        time.Time      `json:"createdAt"`
	DriverName       sql.NullString `json:"driver_name"`
	PlateNumber      string         `json:"plateNumber"`
	VehicleName      string         `json:"vehicle_name"`
	FuelCategoryName FuelCategory   `json:"fuel_category_name"`
}

func (q *Queries) GetFuelExpenseByID(ctx context.Context, id int32) (GetFuelExpenseByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFuelExpenseByID, id)
	var i GetFuelExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.VehicleId,
		&i.FuelTypeId,
		&i.BookingId,
		&i.DriverId,
		&i.RecordedById,
		&i.FuelGrade,
		&i.ProofPhotoUrl,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.DistanceKm,
		&i.Quantity,
		&i.PricePerUnit,
		&i.TotalCost,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.Location,
		&i.StationName,
		&i.Note,
		&i.CreatedAt,
		&i.DriverName,
		&i.PlateNumber,
		&i.VehicleName,
		&i.FuelCategoryName,
	)
	return i, err
}

const getFuelTypeByID = `-- name: GetFuelTypeByID :one
SELECT id, name, type, unit, default_price, is_active, created_at, updated_at FROM fuel_types WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFuelTypeByID(ctx context.Context, id int32) (FuelType, error) {
	row := q.db.QueryRowContext(ctx, getFuelTypeByID, id)
	var i FuelType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFuelExpenses = `-- name: ListFuelExpenses :many
SELECT fe.id, fe."vehicleId", fe."fuelTypeId", fe."bookingId", fe."driverId", fe."recordedById", fe."fuelGrade", fe."proofPhotoUrl", fe."odometerBefore", fe."odometerAfter", fe."distanceKm", fe.quantity, fe."pricePerUnit", fe."totalCost", fe."batteryBefore", fe."batteryAfter", fe.location, fe."stationName", fe.note, fe."createdAt", d_u.name AS driver_name, v."plateNumber", r.name AS vehicle_name, ft.type AS fuel_category_name
FROM fuel_expenses fe
LEFT JOIN drivers d ON d.id = fe."driverId"
LEFT JOIN users d_u ON d_u.id = d."userId"
JOIN vehicles v ON v.id = fe."vehicleId"
JOIN resources r ON r.id = v."resourceId"
JOIN fuel_types ft ON ft.id = fe."fuelTypeId"
WHERE ($3::int IS NULL OR fe."driverId" = $3::int)
  AND ($4::int IS NULL OR fe."vehicleId" = $4::int)
  AND ($5::fuel_category IS NULL OR ft.type = $5::fuel_category)
ORDER BY fe."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListFuelExpensesParams struct {
	Limit        int32            `json:"limit"`
	Offset       int32            `json:"offset"`
	DriverID     sql.NullInt32    `json:"driver_id"`
	VehicleID    sql.NullInt32    `json:"vehicle_id"`
	FuelCategory NullFuelCategory `json:"fuel_category"`
}

type ListFuelExpensesRow struct {
	ID               int32          `json:"id"`
	VehicleId        int32          `json:"vehicleId"`
	FuelTypeId       int32          `json:"fuelTypeId"`
	BookingId        sql.NullInt32  `json:"bookingId"`
	DriverId         sql.NullInt32  `json:"driverId"`
	RecordedById     int32          `json:"recordedById"`
	FuelGrade        sql.NullString `json:"fuelGrade"`
	ProofPhotoUrl    sql.NullString `json:"proofPhotoUrl"`
	OdometerBefore   sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter    sql.NullInt32  `json:"odometerAfter"`
	DistanceKm       sql.NullInt32  `json:"distanceKm"`
	Quantity         sql.NullString `json:"quantity"`
	PricePerUnit     sql.NullString `json:"pricePerUnit"`
	TotalCost        sql.NullString `json:"totalCost"`
	BatteryBefore    sql.NullString `json:"batteryBefore"`
	BatteryAfter     sql.NullString `json:"batteryAfter"`
	Location         string         `json:"location"`
	StationName      sql.NullString `json:"stationName"`
	Note             sql.NullString `json:"note"`
	CreatedAt        time.Time      `json:"createdAt"`
	DriverName       sql.NullString `json:"driver_name"`
	PlateNumber      string         `json:"plateNumber"`
	VehicleName      string         `json:"vehicle_name"`
	FuelCategoryName FuelCategory   `json:"fuel_category_name"`
}

func (q *Queries) ListFuelExpenses(ctx context.Context, arg ListFuelExpensesParams) ([]ListFuelExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFuelExpenses,
		arg.Limit,
		arg.Offset,
		arg.DriverID,
		arg.VehicleID,
		arg.FuelCategory,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFuelExpensesRow
	for rows.Next() {
		var i ListFuelExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleId,
			&i.FuelTypeId,
			&i.BookingId,
			&i.DriverId,
			&i.RecordedById,
			&i.FuelGrade,
			&i.ProofPhotoUrl,
			&i.OdometerBefore,
			&i.OdometerAfter,
			&i.DistanceKm,
			&i.Quantity,
			&i.PricePerUnit,
			&i.TotalCost,
			&i.BatteryBefore,
			&i.BatteryAfter,
			&i.Location,
			&i.StationName,
			&i.Note,
			&i.CreatedAt,
			&i.DriverName,
			&i.PlateNumber,
			&i.VehicleName,
			&i.FuelCategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFuelExpense = `-- name: UpdateFuelExpense :one
UPDATE fuel_expenses
SET "vehicleId" = $2, "fuelTypeId" = $3, "bookingId" = $4, "driverId" = $5,
    "recordedById" = $6, "fuelGrade" = $7, "proofPhotoUrl" = $8,
    "odometerBefore" = $9, "odometerAfter" = $10, "distanceKm" = $11,
    quantity = $12, "pricePerUnit" = $13, "totalCost" = $14,
    "batteryBefore" = $15, "batteryAfter" = $16, location = $17, "stationName" = $18, note = $19
WHERE id = $1 RETURNING id, "vehicleId", "fuelTypeId", "bookingId", "driverId", "recordedById", "fuelGrade", "proofPhotoUrl", "odometerBefore", "odometerAfter", "distanceKm", quantity, "pricePerUnit", "totalCost", "batteryBefore", "batteryAfter", location, "stationName", note, "createdAt"
`

type UpdateFuelExpenseParams struct {
	ID             int32          `json:"id"`
	VehicleId      int32          `json:"vehicleId"`
	FuelTypeId     int32          `json:"fuelTypeId"`
	BookingId      sql.NullInt32  `json:"bookingId"`
	DriverId       sql.NullInt32  `json:"driverId"`
	RecordedById   int32          `json:"recordedById"`
	FuelGrade      sql.NullString `json:"fuelGrade"`
	ProofPhotoUrl  sql.NullString `json:"proofPhotoUrl"`
	OdometerBefore sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter  sql.NullInt32  `json:"odometerAfter"`
	DistanceKm     sql.NullInt32  `json:"distanceKm"`
	Quantity       sql.NullString `json:"quantity"`
	PricePerUnit   sql.NullString `json:"pricePerUnit"`
	TotalCost      sql.NullString `json:"totalCost"`
	BatteryBefore  sql.NullString `json:"batteryBefore"`
	BatteryAfter   sql.NullString `json:"batteryAfter"`
	Location       string         `json:"location"`
	StationName    sql.NullString `json:"stationName"`
	Note           sql.NullString `json:"note"`
}

func (q *Queries) UpdateFuelExpense(ctx context.Context, arg UpdateFuelExpenseParams) (FuelExpense, error) {
	row := q.db.QueryRowContext(ctx, updateFuelExpense,
		arg.ID,
		arg.VehicleId,
		arg.FuelTypeId,
		arg.BookingId,
		arg.DriverId,
		arg.RecordedById,
		arg.FuelGrade,
		arg.ProofPhotoUrl,
		arg.OdometerBefore,
		arg.OdometerAfter,
		arg.DistanceKm,
		arg.Quantity,
		arg.PricePerUnit,
		arg.TotalCost,
		arg.BatteryBefore,
		arg.BatteryAfter,
		arg.Location,
		arg.StationName,
		arg.Note,
	)
	var i FuelExpense
	err := row.Scan(
		&i.ID,
		&i.VehicleId,
		&i.FuelTypeId,
		&i.BookingId,
		&i.DriverId,
		&i.RecordedById,
		&i.FuelGrade,
		&i.ProofPhotoUrl,
		&i.OdometerBefore,
		&i.OdometerAfter,
		&i.DistanceKm,
		&i.Quantity,
		&i.PricePerUnit,
		&i.TotalCost,
		&i.BatteryBefore,
		&i.BatteryAfter,
		&i.Location,
		&i.StationName,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
