// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuel_type.sql

package repository

import (
	"context"
	"database/sql"
)

const createFuelType = `-- name: CreateFuelType :one
INSERT INTO fuel_types (
    name, type, unit, default_price, is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, type, unit, default_price, is_active, created_at, updated_at
`

type CreateFuelTypeParams struct {
	Name         string         `json:"name"`
	Type         FuelCategory   `json:"type"`
	Unit         FuelUnit       `json:"unit"`
	DefaultPrice sql.NullString `json:"default_price"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) CreateFuelType(ctx context.Context, arg CreateFuelTypeParams) (FuelType, error) {
	row := q.db.QueryRowContext(ctx, createFuelType,
		arg.Name,
		arg.Type,
		arg.Unit,
		arg.DefaultPrice,
		arg.IsActive,
	)
	var i FuelType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFuelType = `-- name: DeleteFuelType :exec
DELETE FROM fuel_types
WHERE id = $1
`

func (q *Queries) DeleteFuelType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFuelType, id)
	return err
}

const getFuelType = `-- name: GetFuelType :one
SELECT id, name, type, unit, default_price, is_active, created_at, updated_at FROM fuel_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFuelType(ctx context.Context, id int32) (FuelType, error) {
	row := q.db.QueryRowContext(ctx, getFuelType, id)
	var i FuelType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFuelTypes = `-- name: ListFuelTypes :many
SELECT id, name, type, unit, default_price, is_active, created_at, updated_at FROM fuel_types
ORDER BY id ASC
`

func (q *Queries) ListFuelTypes(ctx context.Context) ([]FuelType, error) {
	rows, err := q.db.QueryContext(ctx, listFuelTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FuelType
	for rows.Next() {
		var i FuelType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Unit,
			&i.DefaultPrice,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFuelType = `-- name: UpdateFuelType :one
UPDATE fuel_types
SET name = $2,
    type = $3,
    unit = $4,
    default_price = $5,
    is_active = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, unit, default_price, is_active, created_at, updated_at
`

type UpdateFuelTypeParams struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Type         FuelCategory   `json:"type"`
	Unit         FuelUnit       `json:"unit"`
	DefaultPrice sql.NullString `json:"default_price"`
	IsActive     bool           `json:"is_active"`
}

func (q *Queries) UpdateFuelType(ctx context.Context, arg UpdateFuelTypeParams) (FuelType, error) {
	row := q.db.QueryRowContext(ctx, updateFuelType,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Unit,
		arg.DefaultPrice,
		arg.IsActive,
	)
	var i FuelType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Unit,
		&i.DefaultPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
