// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guest_booking.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const approveGuestBooking = `-- name: ApproveGuestBooking :one
UPDATE guest_bookings
SET status = 'APPROVED', "approvedById" = $2, "approvedAt" = NOW(), "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "guestName", "guestEmail", "guestPhone", "departmentName", "resourceId", "startDate", "endDate", purpose, status, "accessToken", "approvedById", "approvedAt", "rejectionNote", "returnedAt", "createdAt", "updatedAt"
`

type ApproveGuestBookingParams struct {
	ID           int32         `json:"id"`
	ApprovedById sql.NullInt32 `json:"approvedById"`
}

func (q *Queries) ApproveGuestBooking(ctx context.Context, arg ApproveGuestBookingParams) (GuestBooking, error) {
	row := q.db.QueryRowContext(ctx, approveGuestBooking, arg.ID, arg.ApprovedById)
	var i GuestBooking
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelGuestBookingByToken = `-- name: CancelGuestBookingByToken :one
UPDATE guest_bookings
SET status = 'CANCELLED', "updatedAt" = NOW()
WHERE "accessToken" = $1 RETURNING id, "guestName", "guestEmail", "guestPhone", "departmentName", "resourceId", "startDate", "endDate", purpose, status, "accessToken", "approvedById", "approvedAt", "rejectionNote", "returnedAt", "createdAt", "updatedAt"
`

func (q *Queries) CancelGuestBookingByToken(ctx context.Context, accesstoken string) (GuestBooking, error) {
	row := q.db.QueryRowContext(ctx, cancelGuestBookingByToken, accesstoken)
	var i GuestBooking
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeGuestBookingByToken = `-- name: CompleteGuestBookingByToken :one
UPDATE guest_bookings
SET status = 'COMPLETED', "returnedAt" = NOW(), "updatedAt" = NOW()
WHERE "accessToken" = $1 RETURNING id, "guestName", "guestEmail", "guestPhone", "departmentName", "resourceId", "startDate", "endDate", purpose, status, "accessToken", "approvedById", "approvedAt", "rejectionNote", "returnedAt", "createdAt", "updatedAt"
`

func (q *Queries) CompleteGuestBookingByToken(ctx context.Context, accesstoken string) (GuestBooking, error) {
	row := q.db.QueryRowContext(ctx, completeGuestBookingByToken, accesstoken)
	var i GuestBooking
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countGuestBookings = `-- name: CountGuestBookings :one
SELECT COUNT(*) FROM guest_bookings
WHERE ($1::booking_status IS NULL OR status = $1::booking_status)
`

func (q *Queries) CountGuestBookings(ctx context.Context, status NullBookingStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuestBookings, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestBooking = `-- name: CreateGuestBooking :one
INSERT INTO guest_bookings (
    "guestName", "guestEmail", "guestPhone", "departmentName",
    "resourceId", "startDate", "endDate", purpose, "accessToken"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, "guestName", "guestEmail", "guestPhone", "departmentName", "resourceId", "startDate", "endDate", purpose, status, "accessToken", "approvedById", "approvedAt", "rejectionNote", "returnedAt", "createdAt", "updatedAt"
`

type CreateGuestBookingParams struct {
	GuestName      string    `json:"guestName"`
	GuestEmail     string    `json:"guestEmail"`
	GuestPhone     string    `json:"guestPhone"`
	DepartmentName string    `json:"departmentName"`
	ResourceId     int32     `json:"resourceId"`
	StartDate      time.Time `json:"startDate"`
	EndDate        time.Time `json:"endDate"`
	Purpose        string    `json:"purpose"`
	AccessToken    string    `json:"accessToken"`
}

func (q *Queries) CreateGuestBooking(ctx context.Context, arg CreateGuestBookingParams) (GuestBooking, error) {
	row := q.db.QueryRowContext(ctx, createGuestBooking,
		arg.GuestName,
		arg.GuestEmail,
		arg.GuestPhone,
		arg.DepartmentName,
		arg.ResourceId,
		arg.StartDate,
		arg.EndDate,
		arg.Purpose,
		arg.AccessToken,
	)
	var i GuestBooking
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuestBookingByID = `-- name: GetGuestBookingByID :one
SELECT gb.id, gb."guestName", gb."guestEmail", gb."guestPhone", gb."departmentName", gb."resourceId", gb."startDate", gb."endDate", gb.purpose, gb.status, gb."accessToken", gb."approvedById", gb."approvedAt", gb."rejectionNote", gb."returnedAt", gb."createdAt", gb."updatedAt", r.name AS resource_name, r.type AS resource_type,
       u.name AS approver_name
FROM guest_bookings gb
JOIN resources r ON r.id = gb."resourceId"
LEFT JOIN users u ON u.id = gb."approvedById"
WHERE gb.id = $1 LIMIT 1
`

type GetGuestBookingByIDRow struct {
	ID             int32          `json:"id"`
	GuestName      string         `json:"guestName"`
	GuestEmail     string         `json:"guestEmail"`
	GuestPhone     string         `json:"guestPhone"`
	DepartmentName string         `json:"departmentName"`
	ResourceId     int32          `json:"resourceId"`
	StartDate      time.Time      `json:"startDate"`
	EndDate        time.Time      `json:"endDate"`
	Purpose        string         `json:"purpose"`
	Status         BookingStatus  `json:"status"`
	AccessToken    string         `json:"accessToken"`
	ApprovedById   sql.NullInt32  `json:"approvedById"`
	ApprovedAt     sql.NullTime   `json:"approvedAt"`
	RejectionNote  sql.NullString `json:"rejectionNote"`
	ReturnedAt     sql.NullTime   `json:"returnedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ResourceName   string         `json:"resource_name"`
	ResourceType   ResourceType   `json:"resource_type"`
	ApproverName   sql.NullString `json:"approver_name"`
}

func (q *Queries) GetGuestBookingByID(ctx context.Context, id int32) (GetGuestBookingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGuestBookingByID, id)
	var i GetGuestBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceName,
		&i.ResourceType,
		&i.ApproverName,
	)
	return i, err
}

const getGuestBookingByToken = `-- name: GetGuestBookingByToken :one
SELECT gb.id, gb."guestName", gb."guestEmail", gb."guestPhone", gb."departmentName", gb."resourceId", gb."startDate", gb."endDate", gb.purpose, gb.status, gb."accessToken", gb."approvedById", gb."approvedAt", gb."rejectionNote", gb."returnedAt", gb."createdAt", gb."updatedAt", r.name AS resource_name, r.type AS resource_type
FROM guest_bookings gb
JOIN resources r ON r.id = gb."resourceId"
WHERE gb."accessToken" = $1 LIMIT 1
`

type GetGuestBookingByTokenRow struct {
	ID             int32          `json:"id"`
	GuestName      string         `json:"guestName"`
	GuestEmail     string         `json:"guestEmail"`
	GuestPhone     string         `json:"guestPhone"`
	DepartmentName string         `json:"departmentName"`
	ResourceId     int32          `json:"resourceId"`
	StartDate      time.Time      `json:"startDate"`
	EndDate        time.Time      `json:"endDate"`
	Purpose        string         `json:"purpose"`
	Status         BookingStatus  `json:"status"`
	AccessToken    string         `json:"accessToken"`
	ApprovedById   sql.NullInt32  `json:"approvedById"`
	ApprovedAt     sql.NullTime   `json:"approvedAt"`
	RejectionNote  sql.NullString `json:"rejectionNote"`
	ReturnedAt     sql.NullTime   `json:"returnedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ResourceName   string         `json:"resource_name"`
	ResourceType   ResourceType   `json:"resource_type"`
}

func (q *Queries) GetGuestBookingByToken(ctx context.Context, accesstoken string) (GetGuestBookingByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getGuestBookingByToken, accesstoken)
	var i GetGuestBookingByTokenRow
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceName,
		&i.ResourceType,
	)
	return i, err
}

const listGuestBookings = `-- name: ListGuestBookings :many
SELECT gb.id, gb."guestName", gb."guestEmail", gb."guestPhone", gb."departmentName", gb."resourceId", gb."startDate", gb."endDate", gb.purpose, gb.status, gb."accessToken", gb."approvedById", gb."approvedAt", gb."rejectionNote", gb."returnedAt", gb."createdAt", gb."updatedAt", r.name AS resource_name, r.type AS resource_type,
       u.name AS approver_name
FROM guest_bookings gb
JOIN resources r ON r.id = gb."resourceId"
LEFT JOIN users u ON u.id = gb."approvedById"
WHERE ($3::booking_status IS NULL OR gb.status = $3::booking_status)
ORDER BY gb."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListGuestBookingsParams struct {
	Limit  int32             `json:"limit"`
	Offset int32             `json:"offset"`
	Status NullBookingStatus `json:"status"`
}

type ListGuestBookingsRow struct {
	ID             int32          `json:"id"`
	GuestName      string         `json:"guestName"`
	GuestEmail     string         `json:"guestEmail"`
	GuestPhone     string         `json:"guestPhone"`
	DepartmentName string         `json:"departmentName"`
	ResourceId     int32          `json:"resourceId"`
	StartDate      time.Time      `json:"startDate"`
	EndDate        time.Time      `json:"endDate"`
	Purpose        string         `json:"purpose"`
	Status         BookingStatus  `json:"status"`
	AccessToken    string         `json:"accessToken"`
	ApprovedById   sql.NullInt32  `json:"approvedById"`
	ApprovedAt     sql.NullTime   `json:"approvedAt"`
	RejectionNote  sql.NullString `json:"rejectionNote"`
	ReturnedAt     sql.NullTime   `json:"returnedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	ResourceName   string         `json:"resource_name"`
	ResourceType   ResourceType   `json:"resource_type"`
	ApproverName   sql.NullString `json:"approver_name"`
}

func (q *Queries) ListGuestBookings(ctx context.Context, arg ListGuestBookingsParams) ([]ListGuestBookingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuestBookings, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuestBookingsRow
	for rows.Next() {
		var i ListGuestBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.DepartmentName,
			&i.ResourceId,
			&i.StartDate,
			&i.EndDate,
			&i.Purpose,
			&i.Status,
			&i.AccessToken,
			&i.ApprovedById,
			&i.ApprovedAt,
			&i.RejectionNote,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceName,
			&i.ResourceType,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectGuestBooking = `-- name: RejectGuestBooking :one
UPDATE guest_bookings
SET status = 'REJECTED', "approvedById" = $2, "approvedAt" = NOW(),
    "rejectionNote" = $3, "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "guestName", "guestEmail", "guestPhone", "departmentName", "resourceId", "startDate", "endDate", purpose, status, "accessToken", "approvedById", "approvedAt", "rejectionNote", "returnedAt", "createdAt", "updatedAt"
`

type RejectGuestBookingParams struct {
	ID            int32          `json:"id"`
	ApprovedById  sql.NullInt32  `json:"approvedById"`
	RejectionNote sql.NullString `json:"rejectionNote"`
}

func (q *Queries) RejectGuestBooking(ctx context.Context, arg RejectGuestBookingParams) (GuestBooking, error) {
	row := q.db.QueryRowContext(ctx, rejectGuestBooking, arg.ID, arg.ApprovedById, arg.RejectionNote)
	var i GuestBooking
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startGuestBooking = `-- name: StartGuestBooking :one
UPDATE guest_bookings SET status = 'ONGOING', "updatedAt" = NOW() WHERE id = $1 RETURNING id, "guestName", "guestEmail", "guestPhone", "departmentName", "resourceId", "startDate", "endDate", purpose, status, "accessToken", "approvedById", "approvedAt", "rejectionNote", "returnedAt", "createdAt", "updatedAt"
`

func (q *Queries) StartGuestBooking(ctx context.Context, id int32) (GuestBooking, error) {
	row := q.db.QueryRowContext(ctx, startGuestBooking, id)
	var i GuestBooking
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGuestBookingStatus = `-- name: UpdateGuestBookingStatus :one
UPDATE guest_bookings SET status = $2, "updatedAt" = NOW() WHERE id = $1 RETURNING id, "guestName", "guestEmail", "guestPhone", "departmentName", "resourceId", "startDate", "endDate", purpose, status, "accessToken", "approvedById", "approvedAt", "rejectionNote", "returnedAt", "createdAt", "updatedAt"
`

type UpdateGuestBookingStatusParams struct {
	ID     int32         `json:"id"`
	Status BookingStatus `json:"status"`
}

func (q *Queries) UpdateGuestBookingStatus(ctx context.Context, arg UpdateGuestBookingStatusParams) (GuestBooking, error) {
	row := q.db.QueryRowContext(ctx, updateGuestBookingStatus, arg.ID, arg.Status)
	var i GuestBooking
	err := row.Scan(
		&i.ID,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.DepartmentName,
		&i.ResourceId,
		&i.StartDate,
		&i.EndDate,
		&i.Purpose,
		&i.Status,
		&i.AccessToken,
		&i.ApprovedById,
		&i.ApprovedAt,
		&i.RejectionNote,
		&i.ReturnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
