// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const countMaintenance = `-- name: CountMaintenance :one
SELECT COUNT(*) FROM maintenance_records
WHERE ($1::int IS NULL OR "resourceId" = $1::int)
`

func (q *Queries) CountMaintenance(ctx context.Context, resourceID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMaintenance, resourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenance = `-- name: CreateMaintenance :one
INSERT INTO maintenance_records ("resourceId", description, "startDate", cost, "createdById")
VALUES ($1, $2, $3, $4, $5) RETURNING id, "resourceId", description, "startDate", "endDate", cost, "createdById", "createdAt"
`

type CreateMaintenanceParams struct {
	ResourceId  int32          `json:"resourceId"`
	Description string         `json:"description"`
	StartDate   time.Time      `json:"startDate"`
	Cost        sql.NullString `json:"cost"`
	CreatedById int32          `json:"createdById"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (MaintenanceRecord, error) {
	row := q.db.QueryRowContext(ctx, createMaintenance,
		arg.ResourceId,
		arg.Description,
		arg.StartDate,
		arg.Cost,
		arg.CreatedById,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Cost,
		&i.CreatedById,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaintenance = `-- name: DeleteMaintenance :exec
DELETE FROM maintenance_records WHERE id = $1
`

func (q *Queries) DeleteMaintenance(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenance, id)
	return err
}

const getMaintenanceByID = `-- name: GetMaintenanceByID :one
SELECT mr.id, mr."resourceId", mr.description, mr."startDate", mr."endDate", mr.cost, mr."createdById", mr."createdAt", r.name AS resource_name, r.type AS resource_type,
       u.name AS created_by_name
FROM maintenance_records mr
JOIN resources r ON r.id = mr."resourceId"
JOIN users u ON u.id = mr."createdById"
WHERE mr.id = $1 LIMIT 1
`

type GetMaintenanceByIDRow struct {
	ID            int32          `json:"id"`
	ResourceId    int32          `json:"resourceId"`
	Description   string         `json:"description"`
	StartDate     time.Time      `json:"startDate"`
	EndDate       sql.NullTime   `json:"endDate"`
	Cost          sql.NullString `json:"cost"`
	CreatedById   int32          `json:"createdById"`
	CreatedAt     time.Time      `json:"createdAt"`
	ResourceName  string         `json:"resource_name"`
	ResourceType  ResourceType   `json:"resource_type"`
	CreatedByName string         `json:"created_by_name"`
}

func (q *Queries) GetMaintenanceByID(ctx context.Context, id int32) (GetMaintenanceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceByID, id)
	var i GetMaintenanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Cost,
		&i.CreatedById,
		&i.CreatedAt,
		&i.ResourceName,
		&i.ResourceType,
		&i.CreatedByName,
	)
	return i, err
}

const listMaintenance = `-- name: ListMaintenance :many
SELECT mr.id, mr."resourceId", mr.description, mr."startDate", mr."endDate", mr.cost, mr."createdById", mr."createdAt", r.name AS resource_name, r.type AS resource_type,
       u.name AS created_by_name
FROM maintenance_records mr
JOIN resources r ON r.id = mr."resourceId"
JOIN users u ON u.id = mr."createdById"
WHERE ($3::int IS NULL OR mr."resourceId" = $3::int)
ORDER BY mr."startDate" DESC
LIMIT $1 OFFSET $2
`

type ListMaintenanceParams struct {
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
	ResourceID sql.NullInt32 `json:"resource_id"`
}

type ListMaintenanceRow struct {
	ID            int32          `json:"id"`
	ResourceId    int32          `json:"resourceId"`
	Description   string         `json:"description"`
	StartDate     time.Time      `json:"startDate"`
	EndDate       sql.NullTime   `json:"endDate"`
	Cost          sql.NullString `json:"cost"`
	CreatedById   int32          `json:"createdById"`
	CreatedAt     time.Time      `json:"createdAt"`
	ResourceName  string         `json:"resource_name"`
	ResourceType  ResourceType   `json:"resource_type"`
	CreatedByName string         `json:"created_by_name"`
}

func (q *Queries) ListMaintenance(ctx context.Context, arg ListMaintenanceParams) ([]ListMaintenanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenance, arg.Limit, arg.Offset, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceRow
	for rows.Next() {
		var i ListMaintenanceRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceId,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.Cost,
			&i.CreatedById,
			&i.CreatedAt,
			&i.ResourceName,
			&i.ResourceType,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenance = `-- name: UpdateMaintenance :one
UPDATE maintenance_records
SET description = $2, "startDate" = $3, "endDate" = $4, cost = $5
WHERE id = $1 RETURNING id, "resourceId", description, "startDate", "endDate", cost, "createdById", "createdAt"
`

type UpdateMaintenanceParams struct {
	ID          int32          `json:"id"`
	Description string         `json:"description"`
	StartDate   time.Time      `json:"startDate"`
	EndDate     sql.NullTime   `json:"endDate"`
	Cost        sql.NullString `json:"cost"`
}

func (q *Queries) UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) (MaintenanceRecord, error) {
	row := q.db.QueryRowContext(ctx, updateMaintenance,
		arg.ID,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Cost,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Cost,
		&i.CreatedById,
		&i.CreatedAt,
	)
	return i, err
}
