// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countMaintenance = `-- name: CountMaintenance :one
SELECT COUNT(*) FROM maintenance_records
WHERE ($1::int IS NULL OR "vehicleId" = $1::int)
`

func (q *Queries) CountMaintenance(ctx context.Context, vehicleID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMaintenance, vehicleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenance = `-- name: CreateMaintenance :one
INSERT INTO maintenance_records (
    "vehicleId", "maintenanceTypeId", description, type, status,
    odometer, "totalCost", "vendorName", location, "startDate", "endDate", "completedAt", "proofPhotos", "recordedById", "isAutoGenerated"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING id, "vehicleId", "maintenanceTypeId", description, type, status, "vendorName", "proofPhotos", odometer, "totalCost", location, "startDate", "endDate", "completedAt", "recordedById", "createdAt", "isAutoGenerated"
`

type CreateMaintenanceParams struct {
	VehicleId         int32                 `json:"vehicleId"`
	MaintenanceTypeId sql.NullInt32         `json:"maintenanceTypeId"`
	Description       string                `json:"description"`
	Type              string                `json:"type"`
	Status            string                `json:"status"`
	Odometer          sql.NullInt32         `json:"odometer"`
	TotalCost         sql.NullString        `json:"totalCost"`
	VendorName        sql.NullString        `json:"vendorName"`
	Location          string                `json:"location"`
	StartDate         time.Time             `json:"startDate"`
	EndDate           sql.NullTime          `json:"endDate"`
	CompletedAt       sql.NullTime          `json:"completedAt"`
	ProofPhotos       pqtype.NullRawMessage `json:"proofPhotos"`
	RecordedById      int32                 `json:"recordedById"`
	IsAutoGenerated   bool                  `json:"isAutoGenerated"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (MaintenanceRecord, error) {
	row := q.db.QueryRowContext(ctx, createMaintenance,
		arg.VehicleId,
		arg.MaintenanceTypeId,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Odometer,
		arg.TotalCost,
		arg.VendorName,
		arg.Location,
		arg.StartDate,
		arg.EndDate,
		arg.CompletedAt,
		arg.ProofPhotos,
		arg.RecordedById,
		arg.IsAutoGenerated,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleId,
		&i.MaintenanceTypeId,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.VendorName,
		&i.ProofPhotos,
		&i.Odometer,
		&i.TotalCost,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.RecordedById,
		&i.CreatedAt,
		&i.IsAutoGenerated,
	)
	return i, err
}

const deleteMaintenance = `-- name: DeleteMaintenance :exec
DELETE FROM maintenance_records WHERE id = $1
`

func (q *Queries) DeleteMaintenance(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenance, id)
	return err
}

const getMaintenanceByID = `-- name: GetMaintenanceByID :one
SELECT mr.id, mr."vehicleId", mr."maintenanceTypeId", mr.description, mr.type, mr.status, mr."vendorName", mr."proofPhotos", mr.odometer, mr."totalCost", mr.location, mr."startDate", mr."endDate", mr."completedAt", mr."recordedById", mr."createdAt", mr."isAutoGenerated", r.name AS vehicle_name, v."plateNumber", v."photoUrl" AS vehicle_photo_url,
       u.name AS created_by_name
FROM maintenance_records mr
JOIN vehicles v ON v.id = mr."vehicleId"
JOIN resources r ON r.id = v."resourceId"
JOIN users u ON u.id = mr."recordedById"
WHERE mr.id = $1 LIMIT 1
`

type GetMaintenanceByIDRow struct {
	ID                int32                 `json:"id"`
	VehicleId         int32                 `json:"vehicleId"`
	MaintenanceTypeId sql.NullInt32         `json:"maintenanceTypeId"`
	Description       string                `json:"description"`
	Type              string                `json:"type"`
	Status            string                `json:"status"`
	VendorName        sql.NullString        `json:"vendorName"`
	ProofPhotos       pqtype.NullRawMessage `json:"proofPhotos"`
	Odometer          sql.NullInt32         `json:"odometer"`
	TotalCost         sql.NullString        `json:"totalCost"`
	Location          string                `json:"location"`
	StartDate         time.Time             `json:"startDate"`
	EndDate           sql.NullTime          `json:"endDate"`
	CompletedAt       sql.NullTime          `json:"completedAt"`
	RecordedById      int32                 `json:"recordedById"`
	CreatedAt         time.Time             `json:"createdAt"`
	IsAutoGenerated   bool                  `json:"isAutoGenerated"`
	VehicleName       string                `json:"vehicle_name"`
	PlateNumber       string                `json:"plateNumber"`
	VehiclePhotoUrl   sql.NullString        `json:"vehicle_photo_url"`
	CreatedByName     string                `json:"created_by_name"`
}

func (q *Queries) GetMaintenanceByID(ctx context.Context, id int32) (GetMaintenanceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceByID, id)
	var i GetMaintenanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.VehicleId,
		&i.MaintenanceTypeId,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.VendorName,
		&i.ProofPhotos,
		&i.Odometer,
		&i.TotalCost,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.RecordedById,
		&i.CreatedAt,
		&i.IsAutoGenerated,
		&i.VehicleName,
		&i.PlateNumber,
		&i.VehiclePhotoUrl,
		&i.CreatedByName,
	)
	return i, err
}

const getOngoingAutoMaintenanceByVehicle = `-- name: GetOngoingAutoMaintenanceByVehicle :one
SELECT id, "vehicleId", "maintenanceTypeId", description, type, status, "vendorName", "proofPhotos", odometer, "totalCost", location, "startDate", "endDate", "completedAt", "recordedById", "createdAt", "isAutoGenerated" FROM maintenance_records
WHERE "vehicleId" = $1 AND "isAutoGenerated" = TRUE AND status != 'completed'
ORDER BY "createdAt" DESC LIMIT 1
`

// Guards against creating duplicate auto-triggered maintenance records while one is still open.
func (q *Queries) GetOngoingAutoMaintenanceByVehicle(ctx context.Context, vehicleid int32) (MaintenanceRecord, error) {
	row := q.db.QueryRowContext(ctx, getOngoingAutoMaintenanceByVehicle, vehicleid)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleId,
		&i.MaintenanceTypeId,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.VendorName,
		&i.ProofPhotos,
		&i.Odometer,
		&i.TotalCost,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.RecordedById,
		&i.CreatedAt,
		&i.IsAutoGenerated,
	)
	return i, err
}

const listMaintenance = `-- name: ListMaintenance :many
SELECT mr.id, mr."vehicleId", mr."maintenanceTypeId", mr.description, mr.type, mr.status, mr."vendorName", mr."proofPhotos", mr.odometer, mr."totalCost", mr.location, mr."startDate", mr."endDate", mr."completedAt", mr."recordedById", mr."createdAt", mr."isAutoGenerated", r.name AS vehicle_name, v."plateNumber", v."photoUrl" AS vehicle_photo_url,
       u.name AS created_by_name
FROM maintenance_records mr
JOIN vehicles v ON v.id = mr."vehicleId"
JOIN resources r ON r.id = v."resourceId"
JOIN users u ON u.id = mr."recordedById"
WHERE ($3::int IS NULL OR mr."vehicleId" = $3::int)
ORDER BY mr."startDate" DESC
LIMIT $1 OFFSET $2
`

type ListMaintenanceParams struct {
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
	VehicleID sql.NullInt32 `json:"vehicle_id"`
}

type ListMaintenanceRow struct {
	ID                int32                 `json:"id"`
	VehicleId         int32                 `json:"vehicleId"`
	MaintenanceTypeId sql.NullInt32         `json:"maintenanceTypeId"`
	Description       string                `json:"description"`
	Type              string                `json:"type"`
	Status            string                `json:"status"`
	VendorName        sql.NullString        `json:"vendorName"`
	ProofPhotos       pqtype.NullRawMessage `json:"proofPhotos"`
	Odometer          sql.NullInt32         `json:"odometer"`
	TotalCost         sql.NullString        `json:"totalCost"`
	Location          string                `json:"location"`
	StartDate         time.Time             `json:"startDate"`
	EndDate           sql.NullTime          `json:"endDate"`
	CompletedAt       sql.NullTime          `json:"completedAt"`
	RecordedById      int32                 `json:"recordedById"`
	CreatedAt         time.Time             `json:"createdAt"`
	IsAutoGenerated   bool                  `json:"isAutoGenerated"`
	VehicleName       string                `json:"vehicle_name"`
	PlateNumber       string                `json:"plateNumber"`
	VehiclePhotoUrl   sql.NullString        `json:"vehicle_photo_url"`
	CreatedByName     string                `json:"created_by_name"`
}

func (q *Queries) ListMaintenance(ctx context.Context, arg ListMaintenanceParams) ([]ListMaintenanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenance, arg.Limit, arg.Offset, arg.VehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceRow
	for rows.Next() {
		var i ListMaintenanceRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleId,
			&i.MaintenanceTypeId,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.VendorName,
			&i.ProofPhotos,
			&i.Odometer,
			&i.TotalCost,
			&i.Location,
			&i.StartDate,
			&i.EndDate,
			&i.CompletedAt,
			&i.RecordedById,
			&i.CreatedAt,
			&i.IsAutoGenerated,
			&i.VehicleName,
			&i.PlateNumber,
			&i.VehiclePhotoUrl,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenance = `-- name: UpdateMaintenance :one
UPDATE maintenance_records
SET "vehicleId" = $2, "maintenanceTypeId" = $3, description = $4, type = $5, status = $6,
    odometer = $7, "totalCost" = $8, "vendorName" = $9, location = $10,
    "startDate" = $11, "endDate" = $12, "completedAt" = $13, "proofPhotos" = $14
WHERE id = $1 RETURNING id, "vehicleId", "maintenanceTypeId", description, type, status, "vendorName", "proofPhotos", odometer, "totalCost", location, "startDate", "endDate", "completedAt", "recordedById", "createdAt", "isAutoGenerated"
`

type UpdateMaintenanceParams struct {
	ID                int32                 `json:"id"`
	VehicleId         int32                 `json:"vehicleId"`
	MaintenanceTypeId sql.NullInt32         `json:"maintenanceTypeId"`
	Description       string                `json:"description"`
	Type              string                `json:"type"`
	Status            string                `json:"status"`
	Odometer          sql.NullInt32         `json:"odometer"`
	TotalCost         sql.NullString        `json:"totalCost"`
	VendorName        sql.NullString        `json:"vendorName"`
	Location          string                `json:"location"`
	StartDate         time.Time             `json:"startDate"`
	EndDate           sql.NullTime          `json:"endDate"`
	CompletedAt       sql.NullTime          `json:"completedAt"`
	ProofPhotos       pqtype.NullRawMessage `json:"proofPhotos"`
}

func (q *Queries) UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) (MaintenanceRecord, error) {
	row := q.db.QueryRowContext(ctx, updateMaintenance,
		arg.ID,
		arg.VehicleId,
		arg.MaintenanceTypeId,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Odometer,
		arg.TotalCost,
		arg.VendorName,
		arg.Location,
		arg.StartDate,
		arg.EndDate,
		arg.CompletedAt,
		arg.ProofPhotos,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleId,
		&i.MaintenanceTypeId,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.VendorName,
		&i.ProofPhotos,
		&i.Odometer,
		&i.TotalCost,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.RecordedById,
		&i.CreatedAt,
		&i.IsAutoGenerated,
	)
	return i, err
}
