// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master_setting.sql

package repository

import (
	"context"
	"database/sql"
)

const getMasterSettingByKey = `-- name: GetMasterSettingByKey :one
SELECT id, key, value, unit, description, "updatedAt" FROM master_settings WHERE key = $1 LIMIT 1
`

func (q *Queries) GetMasterSettingByKey(ctx context.Context, key string) (MasterSetting, error) {
	row := q.db.QueryRowContext(ctx, getMasterSettingByKey, key)
	var i MasterSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Unit,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listMasterSettings = `-- name: ListMasterSettings :many
SELECT id, key, value, unit, description, "updatedAt" FROM master_settings ORDER BY key
`

func (q *Queries) ListMasterSettings(ctx context.Context) ([]MasterSetting, error) {
	rows, err := q.db.QueryContext(ctx, listMasterSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterSetting
	for rows.Next() {
		var i MasterSetting
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.Unit,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMasterSetting = `-- name: UpsertMasterSetting :one
INSERT INTO master_settings (key, value, unit, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    unit = EXCLUDED.unit,
    description = EXCLUDED.description,
    "updatedAt" = NOW()
RETURNING id, key, value, unit, description, "updatedAt"
`

type UpsertMasterSettingParams struct {
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Unit        sql.NullString `json:"unit"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpsertMasterSetting(ctx context.Context, arg UpsertMasterSettingParams) (MasterSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertMasterSetting,
		arg.Key,
		arg.Value,
		arg.Unit,
		arg.Description,
	)
	var i MasterSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Unit,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}
