// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ApprovalAction string

const (
	ApprovalActionAPPROVED ApprovalAction = "APPROVED"
	ApprovalActionREJECTED ApprovalAction = "REJECTED"
)

func (e *ApprovalAction) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalAction(s)
	case string:
		*e = ApprovalAction(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalAction: %T", src)
	}
	return nil
}

type NullApprovalAction struct {
	ApprovalAction ApprovalAction `json:"approval_action"`
	Valid          bool           `json:"valid"` // Valid is true if ApprovalAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalAction) Scan(value any) error {
	if value == nil {
		ns.ApprovalAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalAction), nil
}

type BookingStatus string

const (
	BookingStatusPENDING   BookingStatus = "PENDING"
	BookingStatusAPPROVED  BookingStatus = "APPROVED"
	BookingStatusREJECTED  BookingStatus = "REJECTED"
	BookingStatusONGOING   BookingStatus = "ONGOING"
	BookingStatusCOMPLETED BookingStatus = "COMPLETED"
	BookingStatusCANCELLED BookingStatus = "CANCELLED"
	BookingStatusOVERDUE   BookingStatus = "OVERDUE"
)

func (e *BookingStatus) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value any) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type FuelType string

const (
	FuelTypeBBM     FuelType = "BBM"
	FuelTypeLISTRIK FuelType = "LISTRIK"
)

func (e *FuelType) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = FuelType(s)
	case string:
		*e = FuelType(s)
	default:
		return fmt.Errorf("unsupported scan type for FuelType: %T", src)
	}
	return nil
}

type NullFuelType struct {
	FuelType FuelType `json:"fuel_type"`
	Valid    bool     `json:"valid"` // Valid is true if FuelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFuelType) Scan(value any) error {
	if value == nil {
		ns.FuelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FuelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFuelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FuelType), nil
}

type ResourceStatus string

const (
	ResourceStatusAVAILABLE   ResourceStatus = "AVAILABLE"
	ResourceStatusMAINTENANCE ResourceStatus = "MAINTENANCE"
	ResourceStatusINACTIVE    ResourceStatus = "INACTIVE"
)

func (e *ResourceStatus) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceStatus(s)
	case string:
		*e = ResourceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceStatus: %T", src)
	}
	return nil
}

type NullResourceStatus struct {
	ResourceStatus ResourceStatus `json:"resource_status"`
	Valid          bool           `json:"valid"` // Valid is true if ResourceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceStatus) Scan(value any) error {
	if value == nil {
		ns.ResourceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceStatus), nil
}

type ResourceType string

const (
	ResourceTypeVEHICLE ResourceType = "VEHICLE"
	ResourceTypeROOM    ResourceType = "ROOM"
)

func (e *ResourceType) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType `json:"resource_type"`
	Valid        bool         `json:"valid"` // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value any) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type RoleName string

const (
	RoleNameEMPLOYEE RoleName = "EMPLOYEE"
	RoleNameADMIN    RoleName = "ADMIN"
	RoleNameDRIVER   RoleName = "DRIVER"
)

func (e *RoleName) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleName(s)
	case string:
		*e = RoleName(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleName: %T", src)
	}
	return nil
}

type NullRoleName struct {
	RoleName RoleName `json:"role_name"`
	Valid    bool     `json:"valid"` // Valid is true if RoleName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleName) Scan(value any) error {
	if value == nil {
		ns.RoleName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleName), nil
}

type ApprovalLog struct {
	ID         int32          `json:"id"`
	BookingId  int32          `json:"bookingId"`
	ApproverId int32          `json:"approverId"`
	Action     ApprovalAction `json:"action"`
	Note       sql.NullString `json:"note"`
	CreatedAt  time.Time      `json:"createdAt"`
}

type Attachment struct {
	ID           int32          `json:"id"`
	UploadedById int32          `json:"uploadedById"`
	VehicleId    sql.NullInt32  `json:"vehicleId"`
	RoomId       sql.NullInt32  `json:"roomId"`
	BookingId    sql.NullInt32  `json:"bookingId"`
	FilePath     string         `json:"filePath"`
	FileName     string         `json:"fileName"`
	FileType     string         `json:"fileType"`
	FileSize     sql.NullInt32  `json:"fileSize"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"createdAt"`
}

type AuditLog struct {
	ID          int32          `json:"id"`
	UserId      sql.NullInt32  `json:"userId"`
	Action      string         `json:"action"`
	EntityType  string         `json:"entityType"`
	EntityId    sql.NullInt32  `json:"entityId"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
}

type AuditLogResponse struct {
	ID          int32   `json:"id"`
	UserID      *int32  `json:"userId"`
	Action      string  `json:"action"`
	EntityType  string  `json:"entityType"`
	EntityID    *int32  `json:"entityId"`
	Description *string `json:"description"`
	CreatedAt   string  `json:"createdAt"`
	UserName    *string `json:"user_name"`
}

type Booking struct {
	ID                int32         `json:"id"`
	UserId            int32         `json:"userId"`
	ResourceId        int32         `json:"resourceId"`
	StartDate         time.Time     `json:"startDate"`
	EndDate           time.Time     `json:"endDate"`
	Purpose           string        `json:"purpose"`
	Status            BookingStatus `json:"status"`
	ApprovedById      sql.NullInt32 `json:"approvedById"`
	ApprovedAt        sql.NullTime  `json:"approvedAt"`
	AssignedDriverId  sql.NullInt32 `json:"assignedDriverId"`
	AssignedVehicleId sql.NullInt32 `json:"assignedVehicleId"`
	AssignedAt        sql.NullTime  `json:"assignedAt"`
	ReturnedAt        sql.NullTime  `json:"returnedAt"`
	CreatedAt         time.Time     `json:"createdAt"`
	UpdatedAt         time.Time     `json:"updatedAt"`
}

type Department struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type Driver struct {
	ID            int32     `json:"id"`
	UserId        int32     `json:"userId"`
	LicenseNumber string    `json:"licenseNumber"`
	PhoneNumber   string    `json:"phoneNumber"`
	IsActive      bool      `json:"isActive"`
	CreatedAt     time.Time `json:"createdAt"`
}

type DriverAssignment struct {
	ID         int32        `json:"id"`
	DriverId   int32        `json:"driverId"`
	VehicleId  int32        `json:"vehicleId"`
	AssignedAt time.Time    `json:"assignedAt"`
	ReleasedAt sql.NullTime `json:"releasedAt"`
}

type DriverRating struct {
	ID        int32          `json:"id"`
	BookingId int32          `json:"bookingId"`
	DriverId  int32          `json:"driverId"`
	RatedById int32          `json:"ratedById"`
	Rating    int16          `json:"rating"`
	Review    sql.NullString `json:"review"`
	CreatedAt time.Time      `json:"createdAt"`
}

type FuelExpense struct {
	ID             int32          `json:"id"`
	DriverId       int32          `json:"driverId"`
	VehicleId      int32          `json:"vehicleId"`
	BookingId      sql.NullInt32  `json:"bookingId"`
	FuelType       FuelType       `json:"fuelType"`
	Liter          sql.NullString `json:"liter"`
	PricePerLiter  sql.NullString `json:"pricePerLiter"`
	OdometerBefore sql.NullInt32  `json:"odometerBefore"`
	OdometerAfter  sql.NullInt32  `json:"odometerAfter"`
	Kwh            sql.NullString `json:"kwh"`
	PricePerKwh    sql.NullString `json:"pricePerKwh"`
	BatteryBefore  sql.NullString `json:"batteryBefore"`
	BatteryAfter   sql.NullString `json:"batteryAfter"`
	TotalAmount    string         `json:"totalAmount"`
	Note           sql.NullString `json:"note"`
	CreatedAt      time.Time      `json:"createdAt"`
}

type GuestBooking struct {
	ID             int32          `json:"id"`
	GuestName      string         `json:"guestName"`
	GuestEmail     string         `json:"guestEmail"`
	GuestPhone     string         `json:"guestPhone"`
	DepartmentName string         `json:"departmentName"`
	ResourceId     int32          `json:"resourceId"`
	StartDate      time.Time      `json:"startDate"`
	EndDate        time.Time      `json:"endDate"`
	Purpose        string         `json:"purpose"`
	Status         BookingStatus  `json:"status"`
	AccessToken    string         `json:"accessToken"`
	ApprovedById   sql.NullInt32  `json:"approvedById"`
	ApprovedAt     sql.NullTime   `json:"approvedAt"`
	RejectionNote  sql.NullString `json:"rejectionNote"`
	ReturnedAt     sql.NullTime   `json:"returnedAt"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
}

type MaintenanceRecord struct {
	ID          int32          `json:"id"`
	ResourceId  int32          `json:"resourceId"`
	Description string         `json:"description"`
	StartDate   time.Time      `json:"startDate"`
	EndDate     sql.NullTime   `json:"endDate"`
	Cost        sql.NullString `json:"cost"`
	CreatedById int32          `json:"createdById"`
	CreatedAt   time.Time      `json:"createdAt"`
}

type MasterSetting struct {
	ID          int32          `json:"id"`
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Unit        sql.NullString `json:"unit"`
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type PasswordResetOtp struct {
	ID        int32     `json:"id"`
	UserId    int32     `json:"userId"`
	OtpCode   string    `json:"otpCode"`
	ExpiresAt time.Time `json:"expiresAt"`
	IsUsed    bool      `json:"isUsed"`
}

type RefreshToken struct {
	ID        int32     `json:"id"`
	UserId    int32     `json:"userId"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
	Revoked   bool      `json:"revoked"`
}

type Resource struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Type      ResourceType   `json:"type"`
	Status    ResourceStatus `json:"status"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type Role struct {
	ID   int32    `json:"id"`
	Name RoleName `json:"name"`
}

type Room struct {
	ID         int32          `json:"id"`
	ResourceId int32          `json:"resourceId"`
	Location   string         `json:"location"`
	Capacity   int16          `json:"capacity"`
	PhotoUrl   sql.NullString `json:"photoUrl"`
}

type User struct {
	ID           int32          `json:"id"`
	EmployeeId   string         `json:"employeeId"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	ProfilePhoto sql.NullString `json:"profilePhoto"`
	IsActive     bool           `json:"isActive"`
	RoleId       int32          `json:"roleId"`
	DepartmentId int32          `json:"departmentId"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type VActiveBooking struct {
	BookingID          int32          `json:"booking_id"`
	Status             BookingStatus  `json:"status"`
	StartDate          time.Time      `json:"startDate"`
	EndDate            time.Time      `json:"endDate"`
	Purpose            string         `json:"purpose"`
	UserName           string         `json:"user_name"`
	EmployeeId         string         `json:"employeeId"`
	Department         string         `json:"department"`
	ResourceName       string         `json:"resource_name"`
	ResourceType       ResourceType   `json:"resource_type"`
	AssignedDriverID   sql.NullInt32  `json:"assigned_driver_id"`
	AssignedDriverName sql.NullString `json:"assigned_driver_name"`
	DriverPhone        sql.NullString `json:"driver_phone"`
	AssignedVehicleID  sql.NullInt32  `json:"assigned_vehicle_id"`
	VehiclePlate       sql.NullString `json:"vehicle_plate"`
	VehicleCapacity    sql.NullInt16  `json:"vehicle_capacity"`
}

type VDriverRatingsSummary struct {
	DriverID      int32    `json:"driver_id"`
	DriverName    string   `json:"driver_name"`
	EmployeeId    string   `json:"employeeId"`
	IsActive      bool     `json:"isActive"`
	TotalRatings  int64    `json:"total_ratings"`
	AverageRating *float64 `json:"average_rating"`
	Bintang5      int64    `json:"bintang_5"`
	Bintang4      int64    `json:"bintang_4"`
	Bintang3      int64    `json:"bintang_3"`
	Bintang2      int64    `json:"bintang_2"`
	Bintang1      int64    `json:"bintang_1"`
}

type VFuelExpenseSummary struct {
	VehicleID        int32  `json:"vehicle_id"`
	PlateNumber      string `json:"plateNumber"`
	VehicleName      string `json:"vehicle_name"`
	Category         string `json:"category"`
	BbmEntries       int64  `json:"bbm_entries"`
	TotalLiter       any    `json:"total_liter"`
	TotalCostBbm     any    `json:"total_cost_bbm"`
	ListrikEntries   int64  `json:"listrik_entries"`
	TotalKwh         any    `json:"total_kwh"`
	TotalCostListrik any    `json:"total_cost_listrik"`
	GrandTotal       any    `json:"grand_total"`
}

type VVehicleSummary struct {
	ID                int32          `json:"id"`
	VehicleName       string         `json:"vehicle_name"`
	PlateNumber       string         `json:"plateNumber"`
	Category          string         `json:"category"`
	Capacity          int16          `json:"capacity"`
	Status            ResourceStatus `json:"status"`
	CurrentOdometer   int32          `json:"currentOdometer"`
	TotalBookings     int64          `json:"total_bookings"`
	CompletedBookings int64          `json:"completed_bookings"`
	TotalLiterBbm     any            `json:"total_liter_bbm"`
	TotalCostBbm      any            `json:"total_cost_bbm"`
	TotalKwhListrik   any            `json:"total_kwh_listrik"`
	TotalCostListrik  any            `json:"total_cost_listrik"`
	TotalFuelCost     any            `json:"total_fuel_cost"`
}

type Vehicle struct {
	ID              int32          `json:"id"`
	ResourceId      int32          `json:"resourceId"`
	PlateNumber     string         `json:"plateNumber"`
	Brand           string         `json:"brand"`
	Model           string         `json:"model"`
	Year            int16          `json:"year"`
	CurrentOdometer int32          `json:"currentOdometer"`
	CategoryId      int32          `json:"categoryId"`
	Capacity        int16          `json:"capacity"`
	PhotoUrl        sql.NullString `json:"photoUrl"`
}

type VehicleCategory struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
