// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	DashboardSummary(ctx context.Context) (DashboardSummaryRow, error)
}

var _ Querier = (*Queries)(nil)
