// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"database/sql"
)

type Querier interface {
	ApproveBooking(ctx context.Context, arg ApproveBookingParams) (Booking, error)
	ApproveGuestBooking(ctx context.Context, arg ApproveGuestBookingParams) (GuestBooking, error)
	AssignDriverToVehicle(ctx context.Context, arg AssignDriverToVehicleParams) (DriverAssignment, error)
	AssignVehicleToBooking(ctx context.Context, arg AssignVehicleToBookingParams) (Booking, error)
	CancelBooking(ctx context.Context, id int32) (Booking, error)
	CancelGuestBookingByToken(ctx context.Context, accesstoken string) (GuestBooking, error)
	CheckBookingConflict(ctx context.Context, arg CheckBookingConflictParams) (int64, error)
	CheckVehicleConflict(ctx context.Context, arg CheckVehicleConflictParams) (int64, error)
	CompleteBooking(ctx context.Context, id int32) (Booking, error)
	CompleteGuestBookingByToken(ctx context.Context, accesstoken string) (GuestBooking, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountBookings(ctx context.Context, arg CountBookingsParams) (int64, error)
	CountDrivers(ctx context.Context, isActive sql.NullBool) (int64, error)
	CountFuelExpenses(ctx context.Context, arg CountFuelExpensesParams) (int64, error)
	CountGuestBookings(ctx context.Context, status NullBookingStatus) (int64, error)
	CountMaintenance(ctx context.Context, vehicleID sql.NullInt32) (int64, error)
	CountNotificationsByUserID(ctx context.Context, userID int32) (int64, error)
	CountRooms(ctx context.Context, arg CountRoomsParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountVehicles(ctx context.Context, arg CountVehiclesParams) (int64, error)
	CreateApprovalLog(ctx context.Context, arg CreateApprovalLogParams) (ApprovalLog, error)
	CreateAttachmentForBooking(ctx context.Context, arg CreateAttachmentForBookingParams) (Attachment, error)
	CreateAttachmentForRoom(ctx context.Context, arg CreateAttachmentForRoomParams) (Attachment, error)
	CreateAttachmentForVehicle(ctx context.Context, arg CreateAttachmentForVehicleParams) (Attachment, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateDepartment(ctx context.Context, name string) (Department, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreateDriverOvertime(ctx context.Context, arg CreateDriverOvertimeParams) (DriverOvertime, error)
	CreateDriverRating(ctx context.Context, arg CreateDriverRatingParams) (DriverRating, error)
	CreateFuelExpense(ctx context.Context, arg CreateFuelExpenseParams) (FuelExpense, error)
	CreateFuelType(ctx context.Context, arg CreateFuelTypeParams) (FuelType, error)
	CreateGuestBooking(ctx context.Context, arg CreateGuestBookingParams) (GuestBooking, error)
	CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (MaintenanceRecord, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (PasswordResetOtp, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	CreateVehicleCategory(ctx context.Context, name string) (VehicleCategory, error)
	DashboardSummary(ctx context.Context) (DashboardSummaryRow, error)
	DeleteAttachment(ctx context.Context, id int32) error
	DeleteDepartment(ctx context.Context, id int32) error
	DeleteFuelExpense(ctx context.Context, id int32) error
	DeleteFuelType(ctx context.Context, id int32) error
	DeleteMaintenance(ctx context.Context, id int32) error
	DeleteProfilePhoto(ctx context.Context, id int32) (User, error)
	DeleteResource(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteVehicleCategory(ctx context.Context, id int32) error
	GetApprovalLogs(ctx context.Context, bookingid int32) ([]GetApprovalLogsRow, error)
	GetAttachmentByID(ctx context.Context, id int32) (GetAttachmentByIDRow, error)
	GetBookingByID(ctx context.Context, id int32) (GetBookingByIDRow, error)
	GetDepartmentByID(ctx context.Context, id int32) (Department, error)
	GetDriverAssignmentHistory(ctx context.Context, driverid int32) ([]GetDriverAssignmentHistoryRow, error)
	GetDriverByID(ctx context.Context, id int32) (GetDriverByIDRow, error)
	GetDriverByUserID(ctx context.Context, userid int32) (Driver, error)
	GetDriverCurrentAssignment(ctx context.Context, driverid int32) (GetDriverCurrentAssignmentRow, error)
	GetDriverRatingByBooking(ctx context.Context, bookingid int32) (DriverRating, error)
	GetDriverRatings(ctx context.Context, driverid int32) ([]GetDriverRatingsRow, error)
	GetFuelExpenseByID(ctx context.Context, id int32) (GetFuelExpenseByIDRow, error)
	GetFuelType(ctx context.Context, id int32) (FuelType, error)
	GetFuelTypeByID(ctx context.Context, id int32) (FuelType, error)
	GetGuestBookingByID(ctx context.Context, id int32) (GetGuestBookingByIDRow, error)
	GetGuestBookingByToken(ctx context.Context, accesstoken string) (GetGuestBookingByTokenRow, error)
	GetMaintenanceByID(ctx context.Context, id int32) (GetMaintenanceByIDRow, error)
	GetMasterSettingByKey(ctx context.Context, key string) (MasterSetting, error)
	// Guards against creating duplicate auto-triggered maintenance records while one is still open.
	GetOngoingAutoMaintenanceByVehicle(ctx context.Context, vehicleid int32) (MaintenanceRecord, error)
	GetOverlappingPassengerCount(ctx context.Context, arg GetOverlappingPassengerCountParams) (int32, error)
	GetOvertimeByBooking(ctx context.Context, bookingid int32) (DriverOvertime, error)
	GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error)
	GetResourceByID(ctx context.Context, id int32) (Resource, error)
	GetRoomByID(ctx context.Context, id int32) (GetRoomByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmployeeID(ctx context.Context, employeeid string) (User, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetValidOTP(ctx context.Context, arg GetValidOTPParams) (PasswordResetOtp, error)
	GetVehicleByID(ctx context.Context, id int32) (GetVehicleByIDRow, error)
	GetVehicleByPlate(ctx context.Context, platenumber string) (Vehicle, error)
	GetVehicleCategoryByID(ctx context.Context, id int32) (VehicleCategory, error)
	InvalidatePreviousOTPs(ctx context.Context, userid int32) error
	ListAttachmentsByBooking(ctx context.Context, bookingid sql.NullInt32) ([]ListAttachmentsByBookingRow, error)
	ListAttachmentsByRoom(ctx context.Context, roomid sql.NullInt32) ([]ListAttachmentsByRoomRow, error)
	ListAttachmentsByVehicle(ctx context.Context, vehicleid sql.NullInt32) ([]ListAttachmentsByVehicleRow, error)
	ListAvailableDrivers(ctx context.Context, arg ListAvailableDriversParams) ([]ListAvailableDriversRow, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	ListDrivers(ctx context.Context, arg ListDriversParams) ([]ListDriversRow, error)
	ListFuelExpenses(ctx context.Context, arg ListFuelExpensesParams) ([]ListFuelExpensesRow, error)
	ListFuelTypes(ctx context.Context) ([]FuelType, error)
	ListGuestBookings(ctx context.Context, arg ListGuestBookingsParams) ([]ListGuestBookingsRow, error)
	ListMaintenance(ctx context.Context, arg ListMaintenanceParams) ([]ListMaintenanceRow, error)
	ListMasterSettings(ctx context.Context) ([]MasterSetting, error)
	ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error)
	ListOvertimeByDriver(ctx context.Context, driverid int32) ([]ListOvertimeByDriverRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]ListRoomsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVehicleCategories(ctx context.Context) ([]VehicleCategory, error)
	ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]ListVehiclesRow, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID int32) error
	// Booking APPROVED tapi tidak pernah dimulai (tidak jadi ONGOING) selama masa bookingnya → EXPIRED
	MarkExpiredBookings(ctx context.Context) ([]Booking, error)
	// Booking PENDING tapi admin tidak merespons sampai masa bookingnya habis → IGNORED
	MarkIgnoredBookings(ctx context.Context) ([]Booking, error)
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	MarkOTPUsed(ctx context.Context, id int32) error
	// Booking ONGOING tapi lewat endDate → OVERDUE (sudah mulai tapi belum selesai tepat waktu)
	MarkOverdueBookings(ctx context.Context) ([]Booking, error)
	RejectBooking(ctx context.Context, arg RejectBookingParams) (Booking, error)
	RejectGuestBooking(ctx context.Context, arg RejectGuestBookingParams) (GuestBooking, error)
	ReleaseDriver(ctx context.Context, driverid int32) error
	ReportAuditLogs(ctx context.Context, arg ReportAuditLogsParams) ([]ReportAuditLogsRow, error)
	ReportBookingSummary(ctx context.Context, arg ReportBookingSummaryParams) (ReportBookingSummaryRow, error)
	ReportDriverActivity(ctx context.Context) ([]ReportDriverActivityRow, error)
	ReportDriverRatings(ctx context.Context) ([]VDriverRatingsSummary, error)
	// Rekap jumlah trip SPD vs Non-SPD dan total overtime per driver.
	ReportDriverTrips(ctx context.Context, arg ReportDriverTripsParams) ([]ReportDriverTripsRow, error)
	ReportFuelExpenses(ctx context.Context) ([]VFuelExpenseSummary, error)
	ReportMaintenanceCost(ctx context.Context) ([]ReportMaintenanceCostRow, error)
	ReportOverdueBookings(ctx context.Context) ([]ReportOverdueBookingsRow, error)
	ReportResourceUsage(ctx context.Context) ([]VVehicleSummary, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	StartBooking(ctx context.Context, id int32) (Booking, error)
	StartGuestBooking(ctx context.Context, id int32) (GuestBooking, error)
	ToggleDriverActive(ctx context.Context, id int32) (Driver, error)
	ToggleUserActive(ctx context.Context, id int32) (User, error)
	UpdateBookingResource(ctx context.Context, arg UpdateBookingResourceParams) (Booking, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error)
	UpdateFuelExpense(ctx context.Context, arg UpdateFuelExpenseParams) (FuelExpense, error)
	UpdateFuelType(ctx context.Context, arg UpdateFuelTypeParams) (FuelType, error)
	UpdateGuestBookingStatus(ctx context.Context, arg UpdateGuestBookingStatusParams) (GuestBooking, error)
	UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) (MaintenanceRecord, error)
	UpdateMergedBooking(ctx context.Context, arg UpdateMergedBookingParams) (Booking, error)
	UpdateProfilePhoto(ctx context.Context, arg UpdateProfilePhotoParams) (User, error)
	UpdateResourceName(ctx context.Context, arg UpdateResourceNameParams) error
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateRoomPhoto(ctx context.Context, arg UpdateRoomPhotoParams) (Room, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
	UpdateVehicleLastMaintenanceOdometer(ctx context.Context, arg UpdateVehicleLastMaintenanceOdometerParams) error
	// Only moves the odometer forward; ignores lower/stale readings.
	UpdateVehicleOdometer(ctx context.Context, arg UpdateVehicleOdometerParams) (Vehicle, error)
	UpdateVehiclePhoto(ctx context.Context, arg UpdateVehiclePhotoParams) (Vehicle, error)
	UpsertMasterSetting(ctx context.Context, arg UpsertMasterSettingParams) (MasterSetting, error)
}

var _ Querier = (*Queries)(nil)
