// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE ($1::text IS NULL OR "entityType" = $1::text)
  AND ($2::int IS NULL OR "userId" = $2::int)
`

type CountAuditLogsParams struct {
	EntityType sql.NullString `json:"entity_type"`
	UserID     sql.NullInt32  `json:"user_id"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogs, arg.EntityType, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const reportAuditLogs = `-- name: ReportAuditLogs :many
SELECT al.id, al."userId", al.action, al."entityType", al."entityId", al.description, al."createdAt", u.name AS user_name
FROM audit_logs al
LEFT JOIN users u ON u.id = al."userId"
WHERE ($3::text IS NULL OR al."entityType" = $3::text)
  AND ($4::int IS NULL OR al."userId" = $4::int)
ORDER BY al."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ReportAuditLogsParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	EntityType sql.NullString `json:"entity_type"`
	UserID     sql.NullInt32  `json:"user_id"`
}

type ReportAuditLogsRow struct {
	ID          int32          `json:"id"`
	UserId      sql.NullInt32  `json:"userId"`
	Action      string         `json:"action"`
	EntityType  string         `json:"entityType"`
	EntityId    sql.NullInt32  `json:"entityId"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	UserName    sql.NullString `json:"user_name"`
}

func (q *Queries) ReportAuditLogs(ctx context.Context, arg ReportAuditLogsParams) ([]ReportAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, reportAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.EntityType,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportAuditLogsRow
	for rows.Next() {
		var i ReportAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Action,
			&i.EntityType,
			&i.EntityId,
			&i.Description,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportBookingSummary = `-- name: ReportBookingSummary :one
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) AS completed,
    SUM(CASE WHEN status = 'PENDING'   THEN 1 ELSE 0 END) AS pending,
    SUM(CASE WHEN status = 'APPROVED'  THEN 1 ELSE 0 END) AS approved,
    SUM(CASE WHEN status = 'ONGOING'   THEN 1 ELSE 0 END) AS ongoing,
    SUM(CASE WHEN status = 'CANCELLED' THEN 1 ELSE 0 END) AS cancelled,
    SUM(CASE WHEN status = 'REJECTED'  THEN 1 ELSE 0 END) AS rejected,
    SUM(CASE WHEN status = 'OVERDUE'   THEN 1 ELSE 0 END) AS overdue
FROM bookings
WHERE ($1::timestamptz IS NULL OR "startDate" >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR "endDate" <= $2::timestamptz)
`

type ReportBookingSummaryParams struct {
	StartFrom sql.NullTime `json:"start_from"`
	EndTo     sql.NullTime `json:"end_to"`
}

type ReportBookingSummaryRow struct {
	Total     int64 `json:"total"`
	Completed int64 `json:"completed"`
	Pending   int64 `json:"pending"`
	Approved  int64 `json:"approved"`
	Ongoing   int64 `json:"ongoing"`
	Cancelled int64 `json:"cancelled"`
	Rejected  int64 `json:"rejected"`
	Overdue   int64 `json:"overdue"`
}

func (q *Queries) ReportBookingSummary(ctx context.Context, arg ReportBookingSummaryParams) (ReportBookingSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, reportBookingSummary, arg.StartFrom, arg.EndTo)
	var i ReportBookingSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Pending,
		&i.Approved,
		&i.Ongoing,
		&i.Cancelled,
		&i.Rejected,
		&i.Overdue,
	)
	return i, err
}

const reportDriverActivity = `-- name: ReportDriverActivity :many
SELECT d.id AS driver_id, u.name AS driver_name, u."employeeId",
       COUNT(DISTINCT b.id) AS total_bookings,
       SUM(CASE WHEN b.status = 'COMPLETED' THEN 1 ELSE 0 END) AS completed_bookings,
       COALESCE(SUM(fe."totalCost"), 0) AS total_fuel_expenses
FROM drivers d
JOIN users u ON u.id = d."userId"
LEFT JOIN bookings b ON b."assignedDriverId" = d.id
LEFT JOIN fuel_expenses fe ON fe."driverId" = d.id
GROUP BY d.id, u.name, u."employeeId"
ORDER BY total_bookings DESC
`

type ReportDriverActivityRow struct {
	DriverID          int32       `json:"driver_id"`
	DriverName        string      `json:"driver_name"`
	EmployeeId        string      `json:"employeeId"`
	TotalBookings     int64       `json:"total_bookings"`
	CompletedBookings int64       `json:"completed_bookings"`
	TotalFuelExpenses interface{} `json:"total_fuel_expenses"`
}

func (q *Queries) ReportDriverActivity(ctx context.Context) ([]ReportDriverActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, reportDriverActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportDriverActivityRow
	for rows.Next() {
		var i ReportDriverActivityRow
		if err := rows.Scan(
			&i.DriverID,
			&i.DriverName,
			&i.EmployeeId,
			&i.TotalBookings,
			&i.CompletedBookings,
			&i.TotalFuelExpenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDriverRatings = `-- name: ReportDriverRatings :many
SELECT driver_id, driver_name, "employeeId", "isActive", total_ratings, average_rating, bintang_5, bintang_4, bintang_3, bintang_2, bintang_1 FROM v_driver_ratings_summary ORDER BY average_rating DESC NULLS LAST
`

func (q *Queries) ReportDriverRatings(ctx context.Context) ([]VDriverRatingsSummary, error) {
	rows, err := q.db.QueryContext(ctx, reportDriverRatings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VDriverRatingsSummary
	for rows.Next() {
		var i VDriverRatingsSummary
		if err := rows.Scan(
			&i.DriverID,
			&i.DriverName,
			&i.EmployeeId,
			&i.IsActive,
			&i.TotalRatings,
			&i.AverageRating,
			&i.Bintang5,
			&i.Bintang4,
			&i.Bintang3,
			&i.Bintang2,
			&i.Bintang1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDriverTrips = `-- name: ReportDriverTrips :many
SELECT
    d.id AS driver_id, u.name AS driver_name, u."employeeId",
    COUNT(DISTINCT b.id) FILTER (WHERE b."bookingType" = 'SPD')     AS spd_trips,
    COUNT(DISTINCT b.id) FILTER (WHERE b."bookingType" = 'NON_SPD') AS non_spd_trips,
    COUNT(DISTINCT ot.id)                                           AS overtime_trips,
    COALESCE(SUM(ot."overtimeMinutes"), 0)::int                     AS total_overtime_minutes
FROM drivers d
JOIN users u ON u.id = d."userId"
LEFT JOIN bookings b ON b."assignedDriverId" = d.id
    AND b.status = 'COMPLETED'
    AND ($1::timestamptz IS NULL OR b."startDate" >= $1::timestamptz)
    AND ($2::timestamptz IS NULL OR b."endDate" <= $2::timestamptz)
LEFT JOIN driver_overtimes ot ON ot."bookingId" = b.id
GROUP BY d.id, u.name, u."employeeId"
ORDER BY (spd_trips + non_spd_trips) DESC
`

type ReportDriverTripsParams struct {
	StartFrom sql.NullTime `json:"start_from"`
	EndTo     sql.NullTime `json:"end_to"`
}

type ReportDriverTripsRow struct {
	DriverID             int32  `json:"driver_id"`
	DriverName           string `json:"driver_name"`
	EmployeeId           string `json:"employeeId"`
	SpdTrips             int64  `json:"spd_trips"`
	NonSpdTrips          int64  `json:"non_spd_trips"`
	OvertimeTrips        int64  `json:"overtime_trips"`
	TotalOvertimeMinutes int32  `json:"total_overtime_minutes"`
}

// Rekap jumlah trip SPD vs Non-SPD dan total overtime per driver.
func (q *Queries) ReportDriverTrips(ctx context.Context, arg ReportDriverTripsParams) ([]ReportDriverTripsRow, error) {
	rows, err := q.db.QueryContext(ctx, reportDriverTrips, arg.StartFrom, arg.EndTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportDriverTripsRow
	for rows.Next() {
		var i ReportDriverTripsRow
		if err := rows.Scan(
			&i.DriverID,
			&i.DriverName,
			&i.EmployeeId,
			&i.SpdTrips,
			&i.NonSpdTrips,
			&i.OvertimeTrips,
			&i.TotalOvertimeMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportFuelExpenses = `-- name: ReportFuelExpenses :many
SELECT vehicle_id, "plateNumber", vehicle_name, category, bbm_entries, total_liter, total_cost_bbm, listrik_entries, total_kwh, total_cost_listrik, grand_total FROM v_fuel_expense_summary ORDER BY grand_total DESC
`

func (q *Queries) ReportFuelExpenses(ctx context.Context) ([]VFuelExpenseSummary, error) {
	rows, err := q.db.QueryContext(ctx, reportFuelExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VFuelExpenseSummary
	for rows.Next() {
		var i VFuelExpenseSummary
		if err := rows.Scan(
			&i.VehicleID,
			&i.PlateNumber,
			&i.VehicleName,
			&i.Category,
			&i.BbmEntries,
			&i.TotalLiter,
			&i.TotalCostBbm,
			&i.ListrikEntries,
			&i.TotalKwh,
			&i.TotalCostListrik,
			&i.GrandTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportMaintenanceCost = `-- name: ReportMaintenanceCost :many
SELECT mr."vehicleId", r.name AS resource_name, 'VEHICLE' AS resource_type,
       COUNT(mr.id) AS total_records,
       COALESCE(SUM(mr."totalCost"), 0) AS total_cost
FROM maintenance_records mr
JOIN vehicles v ON v.id = mr."vehicleId"
JOIN resources r ON r.id = v."resourceId"
GROUP BY mr."vehicleId", r.name
ORDER BY total_cost DESC
`

type ReportMaintenanceCostRow struct {
	VehicleId    int32       `json:"vehicleId"`
	ResourceName string      `json:"resource_name"`
	ResourceType string      `json:"resource_type"`
	TotalRecords int64       `json:"total_records"`
	TotalCost    interface{} `json:"total_cost"`
}

func (q *Queries) ReportMaintenanceCost(ctx context.Context) ([]ReportMaintenanceCostRow, error) {
	rows, err := q.db.QueryContext(ctx, reportMaintenanceCost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportMaintenanceCostRow
	for rows.Next() {
		var i ReportMaintenanceCostRow
		if err := rows.Scan(
			&i.VehicleId,
			&i.ResourceName,
			&i.ResourceType,
			&i.TotalRecords,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportOverdueBookings = `-- name: ReportOverdueBookings :many
SELECT b.id, b."userId", b."resourceId", b."startDate", b."endDate", b.purpose, b."passengerCount", b.status, b."approvedById", b."approvedAt", b."assignedDriverId", b."assignedVehicleId", b."assignedAt", b."returnedAt", b."createdAt", b."updatedAt", b."originalResourceId", b."bookingType", b."odometerStart", b."startLocation", b."startPhotoUrl",
       u.name AS user_name, u."employeeId",
       r.name AS resource_name, r.type AS resource_type
FROM bookings b
JOIN users u ON u.id = b."userId"
JOIN resources r ON r.id = b."resourceId"
WHERE b.status = 'OVERDUE'
ORDER BY b."endDate" ASC
`

type ReportOverdueBookingsRow struct {
	ID                 int32          `json:"id"`
	UserId             int32          `json:"userId"`
	ResourceId         int32          `json:"resourceId"`
	StartDate          time.Time      `json:"startDate"`
	EndDate            time.Time      `json:"endDate"`
	Purpose            string         `json:"purpose"`
	PassengerCount     int32          `json:"passengerCount"`
	Status             BookingStatus  `json:"status"`
	ApprovedById       sql.NullInt32  `json:"approvedById"`
	ApprovedAt         sql.NullTime   `json:"approvedAt"`
	AssignedDriverId   sql.NullInt32  `json:"assignedDriverId"`
	AssignedVehicleId  sql.NullInt32  `json:"assignedVehicleId"`
	AssignedAt         sql.NullTime   `json:"assignedAt"`
	ReturnedAt         sql.NullTime   `json:"returnedAt"`
	CreatedAt          time.Time      `json:"createdAt"`
	UpdatedAt          time.Time      `json:"updatedAt"`
	OriginalResourceId sql.NullInt32  `json:"originalResourceId"`
	BookingType        BookingType    `json:"bookingType"`
	OdometerStart      sql.NullInt32  `json:"odometerStart"`
	StartLocation      sql.NullString `json:"startLocation"`
	StartPhotoUrl      sql.NullString `json:"startPhotoUrl"`
	UserName           string         `json:"user_name"`
	EmployeeId         string         `json:"employeeId"`
	ResourceName       string         `json:"resource_name"`
	ResourceType       ResourceType   `json:"resource_type"`
}

func (q *Queries) ReportOverdueBookings(ctx context.Context) ([]ReportOverdueBookingsRow, error) {
	rows, err := q.db.QueryContext(ctx, reportOverdueBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportOverdueBookingsRow
	for rows.Next() {
		var i ReportOverdueBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.ResourceId,
			&i.StartDate,
			&i.EndDate,
			&i.Purpose,
			&i.PassengerCount,
			&i.Status,
			&i.ApprovedById,
			&i.ApprovedAt,
			&i.AssignedDriverId,
			&i.AssignedVehicleId,
			&i.AssignedAt,
			&i.ReturnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalResourceId,
			&i.BookingType,
			&i.OdometerStart,
			&i.StartLocation,
			&i.StartPhotoUrl,
			&i.UserName,
			&i.EmployeeId,
			&i.ResourceName,
			&i.ResourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportResourceUsage = `-- name: ReportResourceUsage :many
SELECT id, vehicle_name, "plateNumber", category, capacity, status, "currentOdometer", total_bookings, completed_bookings, total_liter_bbm, total_cost_bbm, total_kwh_listrik, total_cost_listrik, total_fuel_cost FROM v_vehicle_summary ORDER BY total_bookings DESC
`

func (q *Queries) ReportResourceUsage(ctx context.Context) ([]VVehicleSummary, error) {
	rows, err := q.db.QueryContext(ctx, reportResourceUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VVehicleSummary
	for rows.Next() {
		var i VVehicleSummary
		if err := rows.Scan(
			&i.ID,
			&i.VehicleName,
			&i.PlateNumber,
			&i.Category,
			&i.Capacity,
			&i.Status,
			&i.CurrentOdometer,
			&i.TotalBookings,
			&i.CompletedBookings,
			&i.TotalLiterBbm,
			&i.TotalCostBbm,
			&i.TotalKwhListrik,
			&i.TotalCostListrik,
			&i.TotalFuelCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
