// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package repository

import (
	"context"
	"database/sql"
)

const countRooms = `-- name: CountRooms :one
SELECT COUNT(*) FROM rooms rm
JOIN resources r ON r.id = rm."resourceId"
WHERE ($1::text IS NULL
       OR r.name ILIKE '%' || $1::text || '%')
  AND ($2::resource_status IS NULL OR r.status = $2::resource_status)
  AND ($2::resource_status IS DISTINCT FROM 'AVAILABLE'::resource_status
       OR NOT EXISTS (
           SELECT 1 FROM bookings bk
           WHERE bk."resourceId" = r.id
             AND bk.status IN ('APPROVED', 'ONGOING')
             AND NOW() BETWEEN bk."startDate" AND bk."endDate"
       ))
`

type CountRoomsParams struct {
	Search sql.NullString     `json:"search"`
	Status NullResourceStatus `json:"status"`
}

func (q *Queries) CountRooms(ctx context.Context, arg CountRoomsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRooms, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms ("resourceId", location, capacity) VALUES ($1, $2, $3) RETURNING id, "resourceId", location, capacity, "photoUrl"
`

type CreateRoomParams struct {
	ResourceId int32  `json:"resourceId"`
	Location   string `json:"location"`
	Capacity   int16  `json:"capacity"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.ResourceId, arg.Location, arg.Capacity)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.Location,
		&i.Capacity,
		&i.PhotoUrl,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT rm.id, rm."resourceId", rm.location, rm.capacity, rm."photoUrl", r.name AS resource_name, r.status AS resource_status
FROM rooms rm
JOIN resources r ON r.id = rm."resourceId"
WHERE rm.id = $1 LIMIT 1
`

type GetRoomByIDRow struct {
	ID             int32          `json:"id"`
	ResourceId     int32          `json:"resourceId"`
	Location       string         `json:"location"`
	Capacity       int16          `json:"capacity"`
	PhotoUrl       sql.NullString `json:"photoUrl"`
	ResourceName   string         `json:"resource_name"`
	ResourceStatus ResourceStatus `json:"resource_status"`
}

func (q *Queries) GetRoomByID(ctx context.Context, id int32) (GetRoomByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i GetRoomByIDRow
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.Location,
		&i.Capacity,
		&i.PhotoUrl,
		&i.ResourceName,
		&i.ResourceStatus,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT rm.id, rm."resourceId", rm.location, rm.capacity, rm."photoUrl", r.name AS resource_name, r.status AS resource_status
FROM rooms rm
JOIN resources r ON r.id = rm."resourceId"
WHERE ($3::text IS NULL
       OR r.name ILIKE '%' || $3::text || '%'
       OR rm.location ILIKE '%' || $3::text || '%')
  AND ($4::resource_status IS NULL OR r.status = $4::resource_status)
  AND ($4::resource_status IS DISTINCT FROM 'AVAILABLE'::resource_status
       OR NOT EXISTS (
           SELECT 1 FROM bookings bk
           WHERE bk."resourceId" = r.id
             AND bk.status IN ('APPROVED', 'ONGOING')
             AND NOW() BETWEEN bk."startDate" AND bk."endDate"
       ))
ORDER BY r."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32              `json:"limit"`
	Offset int32              `json:"offset"`
	Search sql.NullString     `json:"search"`
	Status NullResourceStatus `json:"status"`
}

type ListRoomsRow struct {
	ID             int32          `json:"id"`
	ResourceId     int32          `json:"resourceId"`
	Location       string         `json:"location"`
	Capacity       int16          `json:"capacity"`
	PhotoUrl       sql.NullString `json:"photoUrl"`
	ResourceName   string         `json:"resource_name"`
	ResourceStatus ResourceStatus `json:"resource_status"`
}

// Saat status filter = AVAILABLE, resource yang punya booking APPROVED/ONGOING
// yang overlap dengan waktu sekarang ikut disembunyikan — lihat catatan di ListVehicles.
func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]ListRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRooms,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsRow
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceId,
			&i.Location,
			&i.Capacity,
			&i.PhotoUrl,
			&i.ResourceName,
			&i.ResourceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms SET location = $2, capacity = $3 WHERE id = $1 RETURNING id, "resourceId", location, capacity, "photoUrl"
`

type UpdateRoomParams struct {
	ID       int32  `json:"id"`
	Location string `json:"location"`
	Capacity int16  `json:"capacity"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom, arg.ID, arg.Location, arg.Capacity)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.Location,
		&i.Capacity,
		&i.PhotoUrl,
	)
	return i, err
}

const updateRoomPhoto = `-- name: UpdateRoomPhoto :one
UPDATE rooms SET "photoUrl" = $2 WHERE id = $1 RETURNING id, "resourceId", location, capacity, "photoUrl"
`

type UpdateRoomPhotoParams struct {
	ID       int32          `json:"id"`
	PhotoUrl sql.NullString `json:"photoUrl"`
}

func (q *Queries) UpdateRoomPhoto(ctx context.Context, arg UpdateRoomPhotoParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoomPhoto, arg.ID, arg.PhotoUrl)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.Location,
		&i.Capacity,
		&i.PhotoUrl,
	)
	return i, err
}
