// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_keeper.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const countRoomKeepers = `-- name: CountRoomKeepers :one
SELECT COUNT(*) FROM room_keepers rk
WHERE ($1::boolean IS NULL OR rk."isActive" = $1::boolean)
`

func (q *Queries) CountRoomKeepers(ctx context.Context, isActive sql.NullBool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoomKeepers, isActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoomKeeper = `-- name: CreateRoomKeeper :one
INSERT INTO room_keepers ("userId", "phoneNumber", "isActive")
VALUES ($1, $2, TRUE) RETURNING id, "userId", "phoneNumber", "isActive", "createdAt"
`

type CreateRoomKeeperParams struct {
	UserId      int32  `json:"userId"`
	PhoneNumber string `json:"phoneNumber"`
}

func (q *Queries) CreateRoomKeeper(ctx context.Context, arg CreateRoomKeeperParams) (RoomKeeper, error) {
	row := q.db.QueryRowContext(ctx, createRoomKeeper, arg.UserId, arg.PhoneNumber)
	var i RoomKeeper
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomKeeperByID = `-- name: GetRoomKeeperByID :one
SELECT rk.id, rk."userId", rk."phoneNumber", rk."isActive", rk."createdAt", u.name AS user_name, u."employeeId", u.email, u."profilePhoto"
FROM room_keepers rk
JOIN users u ON u.id = rk."userId"
WHERE rk.id = $1 LIMIT 1
`

type GetRoomKeeperByIDRow struct {
	ID           int32          `json:"id"`
	UserId       int32          `json:"userId"`
	PhoneNumber  string         `json:"phoneNumber"`
	IsActive     bool           `json:"isActive"`
	CreatedAt    time.Time      `json:"createdAt"`
	UserName     string         `json:"user_name"`
	EmployeeId   string         `json:"employeeId"`
	Email        string         `json:"email"`
	ProfilePhoto sql.NullString `json:"profilePhoto"`
}

func (q *Queries) GetRoomKeeperByID(ctx context.Context, id int32) (GetRoomKeeperByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomKeeperByID, id)
	var i GetRoomKeeperByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserName,
		&i.EmployeeId,
		&i.Email,
		&i.ProfilePhoto,
	)
	return i, err
}

const listRoomKeepers = `-- name: ListRoomKeepers :many
SELECT rk.id, rk."userId", rk."phoneNumber", rk."isActive", rk."createdAt", u.name AS user_name, u."employeeId", u.email
FROM room_keepers rk
JOIN users u ON u.id = rk."userId"
WHERE ($3::boolean IS NULL OR rk."isActive" = $3::boolean)
ORDER BY rk."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListRoomKeepersParams struct {
	Limit    int32        `json:"limit"`
	Offset   int32        `json:"offset"`
	IsActive sql.NullBool `json:"is_active"`
}

type ListRoomKeepersRow struct {
	ID          int32     `json:"id"`
	UserId      int32     `json:"userId"`
	PhoneNumber string    `json:"phoneNumber"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
	UserName    string    `json:"user_name"`
	EmployeeId  string    `json:"employeeId"`
	Email       string    `json:"email"`
}

func (q *Queries) ListRoomKeepers(ctx context.Context, arg ListRoomKeepersParams) ([]ListRoomKeepersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomKeepers, arg.Limit, arg.Offset, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomKeepersRow
	for rows.Next() {
		var i ListRoomKeepersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.PhoneNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UserName,
			&i.EmployeeId,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRoomKeeperActive = `-- name: ToggleRoomKeeperActive :one
UPDATE room_keepers SET "isActive" = NOT "isActive" WHERE id = $1 RETURNING id, "userId", "phoneNumber", "isActive", "createdAt"
`

func (q *Queries) ToggleRoomKeeperActive(ctx context.Context, id int32) (RoomKeeper, error) {
	row := q.db.QueryRowContext(ctx, toggleRoomKeeperActive, id)
	var i RoomKeeper
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoomKeeper = `-- name: UpdateRoomKeeper :one
UPDATE room_keepers SET "phoneNumber" = $2 WHERE id = $1 RETURNING id, "userId", "phoneNumber", "isActive", "createdAt"
`

type UpdateRoomKeeperParams struct {
	ID          int32  `json:"id"`
	PhoneNumber string `json:"phoneNumber"`
}

func (q *Queries) UpdateRoomKeeper(ctx context.Context, arg UpdateRoomKeeperParams) (RoomKeeper, error) {
	row := q.db.QueryRowContext(ctx, updateRoomKeeper, arg.ID, arg.PhoneNumber)
	var i RoomKeeper
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
