// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users u
WHERE ($1::text IS NULL
       OR u.name ILIKE '%' || $1::text || '%'
       OR u.email ILIKE '%' || $1::text || '%'
       OR u."employeeId" ILIKE '%' || $1::text || '%')
  AND ($2::int IS NULL OR u."roleId" = $2::int)
  AND ($3::boolean IS NULL OR u."isActive" = $3::boolean)
`

type CountUsersParams struct {
	Search   sql.NullString `json:"search"`
	RoleID   sql.NullInt32  `json:"role_id"`
	IsActive sql.NullBool   `json:"is_active"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, arg.Search, arg.RoleID, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users ("employeeId", name, email, password, "isActive", "roleId", "departmentId")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, "employeeId", name, email, password, "profilePhoto", "isActive", "roleId", "departmentId", "createdAt", "updatedAt"
`

type CreateUserParams struct {
	EmployeeId   string `json:"employeeId"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	IsActive     bool   `json:"isActive"`
	RoleId       int32  `json:"roleId"`
	DepartmentId int32  `json:"departmentId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.EmployeeId,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.IsActive,
		arg.RoleId,
		arg.DepartmentId,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfilePhoto = `-- name: DeleteProfilePhoto :one
UPDATE users SET "profilePhoto" = NULL, "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "employeeId", name, email, password, "profilePhoto", "isActive", "roleId", "departmentId", "createdAt", "updatedAt"
`

func (q *Queries) DeleteProfilePhoto(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteProfilePhoto, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmployeeID = `-- name: GetUserByEmployeeID :one
SELECT id, "employeeId", name, email, password, "profilePhoto", "isActive", "roleId", "departmentId", "createdAt", "updatedAt" FROM users WHERE "employeeId" = $1 LIMIT 1
`

func (q *Queries) GetUserByEmployeeID(ctx context.Context, employeeid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmployeeID, employeeid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, "createdAt" FROM departments ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name FROM roles ORDER BY id
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u."employeeId", u.name, u.email, u.password, u."profilePhoto", u."isActive", u."roleId", u."departmentId", u."createdAt", u."updatedAt", r.name AS role_name, d.name AS department_name
FROM users u
JOIN roles r ON r.id = u."roleId"
JOIN departments d ON d.id = u."departmentId"
WHERE ($3::text IS NULL
       OR u.name ILIKE '%' || $3::text || '%'
       OR u.email ILIKE '%' || $3::text || '%'
       OR u."employeeId" ILIKE '%' || $3::text || '%')
  AND ($4::int IS NULL OR u."roleId" = $4::int)
  AND ($5::boolean IS NULL OR u."isActive" = $5::boolean)
ORDER BY u."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
	Search   sql.NullString `json:"search"`
	RoleID   sql.NullInt32  `json:"role_id"`
	IsActive sql.NullBool   `json:"is_active"`
}

type ListUsersRow struct {
	ID             int32          `json:"id"`
	EmployeeId     string         `json:"employeeId"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Password       string         `json:"password"`
	ProfilePhoto   sql.NullString `json:"profilePhoto"`
	IsActive       bool           `json:"isActive"`
	RoleId         int32          `json:"roleId"`
	DepartmentId   int32          `json:"departmentId"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
	RoleName       RoleName       `json:"role_name"`
	DepartmentName string         `json:"department_name"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.RoleID,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeId,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.ProfilePhoto,
			&i.IsActive,
			&i.RoleId,
			&i.DepartmentId,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUserActive = `-- name: ToggleUserActive :one
UPDATE users SET "isActive" = NOT "isActive", "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "employeeId", name, email, password, "profilePhoto", "isActive", "roleId", "departmentId", "createdAt", "updatedAt"
`

func (q *Queries) ToggleUserActive(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, toggleUserActive, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfilePhoto = `-- name: UpdateProfilePhoto :one
UPDATE users SET "profilePhoto" = $2, "updatedAt" = NOW()
WHERE id = $1 RETURNING id, "employeeId", name, email, password, "profilePhoto", "isActive", "roleId", "departmentId", "createdAt", "updatedAt"
`

type UpdateProfilePhotoParams struct {
	ID           int32          `json:"id"`
	ProfilePhoto sql.NullString `json:"profilePhoto"`
}

func (q *Queries) UpdateProfilePhoto(ctx context.Context, arg UpdateProfilePhotoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateProfilePhoto, arg.ID, arg.ProfilePhoto)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3, "roleId" = $4, "departmentId" = $5, "updatedAt" = NOW()
WHERE id = $1
RETURNING id, "employeeId", name, email, password, "profilePhoto", "isActive", "roleId", "departmentId", "createdAt", "updatedAt"
`

type UpdateUserParams struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	RoleId       int32  `json:"roleId"`
	DepartmentId int32  `json:"departmentId"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.RoleId,
		arg.DepartmentId,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeId,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.ProfilePhoto,
		&i.IsActive,
		&i.RoleId,
		&i.DepartmentId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
