// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle.sql

package repository

import (
	"context"
	"database/sql"
)

const countVehicles = `-- name: CountVehicles :one
SELECT COUNT(*) FROM vehicles v
JOIN resources r ON r.id = v."resourceId"
WHERE ($1::text IS NULL
       OR r.name ILIKE '%' || $1::text || '%'
       OR v."plateNumber" ILIKE '%' || $1::text || '%')
  AND ($2::int IS NULL OR v."categoryId" = $2::int)
  AND ($3::resource_status IS NULL OR r.status = $3::resource_status)
`

type CountVehiclesParams struct {
	Search     sql.NullString     `json:"search"`
	CategoryID sql.NullInt32      `json:"category_id"`
	Status     NullResourceStatus `json:"status"`
}

func (q *Queries) CountVehicles(ctx context.Context, arg CountVehiclesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVehicles, arg.Search, arg.CategoryID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (name, type, status) VALUES ($1, $2, 'AVAILABLE') RETURNING id, name, type, status, "createdAt", "updatedAt"
`

type CreateResourceParams struct {
	Name string       `json:"name"`
	Type ResourceType `json:"type"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource, arg.Name, arg.Type)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles ("resourceId", "plateNumber", brand, model, year,
                       "currentOdometer", "categoryId", capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, "resourceId", "plateNumber", brand, model, year, "currentOdometer", "categoryId", capacity, "photoUrl", energy_type
`

type CreateVehicleParams struct {
	ResourceId      int32  `json:"resourceId"`
	PlateNumber     string `json:"plateNumber"`
	Brand           string `json:"brand"`
	Model           string `json:"model"`
	Year            int16  `json:"year"`
	CurrentOdometer int32  `json:"currentOdometer"`
	CategoryId      int32  `json:"categoryId"`
	Capacity        int16  `json:"capacity"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, createVehicle,
		arg.ResourceId,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.CurrentOdometer,
		arg.CategoryId,
		arg.Capacity,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometer,
		&i.CategoryId,
		&i.Capacity,
		&i.PhotoUrl,
		&i.EnergyType,
	)
	return i, err
}

const createVehicleCategory = `-- name: CreateVehicleCategory :one
INSERT INTO vehicle_categories (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateVehicleCategory(ctx context.Context, name string) (VehicleCategory, error) {
	row := q.db.QueryRowContext(ctx, createVehicleCategory, name)
	var i VehicleCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const deleteVehicleCategory = `-- name: DeleteVehicleCategory :exec
DELETE FROM vehicle_categories WHERE id = $1
`

func (q *Queries) DeleteVehicleCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteVehicleCategory, id)
	return err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, name, type, status, "createdAt", "updatedAt" FROM resources WHERE id = $1 LIMIT 1
`

func (q *Queries) GetResourceByID(ctx context.Context, id int32) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResourceByID, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT v.id, v."resourceId", v."plateNumber", v.brand, v.model, v.year, v."currentOdometer", v."categoryId", v.capacity, v."photoUrl", v.energy_type, r.name AS resource_name, r.status AS resource_status,
       vc.name AS category_name
FROM vehicles v
JOIN resources r ON r.id = v."resourceId"
JOIN vehicle_categories vc ON vc.id = v."categoryId"
WHERE v.id = $1 LIMIT 1
`

type GetVehicleByIDRow struct {
	ID              int32          `json:"id"`
	ResourceId      int32          `json:"resourceId"`
	PlateNumber     string         `json:"plateNumber"`
	Brand           string         `json:"brand"`
	Model           string         `json:"model"`
	Year            int16          `json:"year"`
	CurrentOdometer int32          `json:"currentOdometer"`
	CategoryId      int32          `json:"categoryId"`
	Capacity        int16          `json:"capacity"`
	PhotoUrl        sql.NullString `json:"photoUrl"`
	EnergyType      EnergyType     `json:"energy_type"`
	ResourceName    string         `json:"resource_name"`
	ResourceStatus  ResourceStatus `json:"resource_status"`
	CategoryName    string         `json:"category_name"`
}

func (q *Queries) GetVehicleByID(ctx context.Context, id int32) (GetVehicleByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleByID, id)
	var i GetVehicleByIDRow
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometer,
		&i.CategoryId,
		&i.Capacity,
		&i.PhotoUrl,
		&i.EnergyType,
		&i.ResourceName,
		&i.ResourceStatus,
		&i.CategoryName,
	)
	return i, err
}

const getVehicleByPlate = `-- name: GetVehicleByPlate :one
SELECT id, "resourceId", "plateNumber", brand, model, year, "currentOdometer", "categoryId", capacity, "photoUrl", energy_type FROM vehicles WHERE "plateNumber" = $1 LIMIT 1
`

func (q *Queries) GetVehicleByPlate(ctx context.Context, platenumber string) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, getVehicleByPlate, platenumber)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometer,
		&i.CategoryId,
		&i.Capacity,
		&i.PhotoUrl,
		&i.EnergyType,
	)
	return i, err
}

const getVehicleCategoryByID = `-- name: GetVehicleCategoryByID :one
SELECT id, name FROM vehicle_categories WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVehicleCategoryByID(ctx context.Context, id int32) (VehicleCategory, error) {
	row := q.db.QueryRowContext(ctx, getVehicleCategoryByID, id)
	var i VehicleCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listVehicleCategories = `-- name: ListVehicleCategories :many
SELECT id, name FROM vehicle_categories ORDER BY name
`

func (q *Queries) ListVehicleCategories(ctx context.Context) ([]VehicleCategory, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleCategory
	for rows.Next() {
		var i VehicleCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT v.id, v."resourceId", v."plateNumber", v.brand, v.model, v.year, v."currentOdometer", v."categoryId", v.capacity, v."photoUrl", v.energy_type, r.name AS resource_name, r.status AS resource_status,
       vc.name AS category_name
FROM vehicles v
JOIN resources r ON r.id = v."resourceId"
JOIN vehicle_categories vc ON vc.id = v."categoryId"
WHERE ($3::text IS NULL
       OR r.name ILIKE '%' || $3::text || '%'
       OR v."plateNumber" ILIKE '%' || $3::text || '%'
       OR v.brand ILIKE '%' || $3::text || '%')
  AND ($4::int IS NULL OR v."categoryId" = $4::int)
  AND ($5::resource_status IS NULL OR r.status = $5::resource_status)
ORDER BY r."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListVehiclesParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	Search     sql.NullString     `json:"search"`
	CategoryID sql.NullInt32      `json:"category_id"`
	Status     NullResourceStatus `json:"status"`
}

type ListVehiclesRow struct {
	ID              int32          `json:"id"`
	ResourceId      int32          `json:"resourceId"`
	PlateNumber     string         `json:"plateNumber"`
	Brand           string         `json:"brand"`
	Model           string         `json:"model"`
	Year            int16          `json:"year"`
	CurrentOdometer int32          `json:"currentOdometer"`
	CategoryId      int32          `json:"categoryId"`
	Capacity        int16          `json:"capacity"`
	PhotoUrl        sql.NullString `json:"photoUrl"`
	EnergyType      EnergyType     `json:"energy_type"`
	ResourceName    string         `json:"resource_name"`
	ResourceStatus  ResourceStatus `json:"resource_status"`
	CategoryName    string         `json:"category_name"`
}

func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]ListVehiclesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicles,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.CategoryID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiclesRow
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceId,
			&i.PlateNumber,
			&i.Brand,
			&i.Model,
			&i.Year,
			&i.CurrentOdometer,
			&i.CategoryId,
			&i.Capacity,
			&i.PhotoUrl,
			&i.EnergyType,
			&i.ResourceName,
			&i.ResourceStatus,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceName = `-- name: UpdateResourceName :exec
UPDATE resources SET name = $2, "updatedAt" = NOW() WHERE id = $1
`

type UpdateResourceNameParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateResourceName(ctx context.Context, arg UpdateResourceNameParams) error {
	_, err := q.db.ExecContext(ctx, updateResourceName, arg.ID, arg.Name)
	return err
}

const updateResourceStatus = `-- name: UpdateResourceStatus :one
UPDATE resources SET status = $2, "updatedAt" = NOW() WHERE id = $1 RETURNING id, name, type, status, "createdAt", "updatedAt"
`

type UpdateResourceStatusParams struct {
	ID     int32          `json:"id"`
	Status ResourceStatus `json:"status"`
}

func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResourceStatus, arg.ID, arg.Status)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET "plateNumber" = $2, brand = $3, model = $4, year = $5,
    "currentOdometer" = $6, "categoryId" = $7, capacity = $8
WHERE id = $1 RETURNING id, "resourceId", "plateNumber", brand, model, year, "currentOdometer", "categoryId", capacity, "photoUrl", energy_type
`

type UpdateVehicleParams struct {
	ID              int32  `json:"id"`
	PlateNumber     string `json:"plateNumber"`
	Brand           string `json:"brand"`
	Model           string `json:"model"`
	Year            int16  `json:"year"`
	CurrentOdometer int32  `json:"currentOdometer"`
	CategoryId      int32  `json:"categoryId"`
	Capacity        int16  `json:"capacity"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, updateVehicle,
		arg.ID,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.CurrentOdometer,
		arg.CategoryId,
		arg.Capacity,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometer,
		&i.CategoryId,
		&i.Capacity,
		&i.PhotoUrl,
		&i.EnergyType,
	)
	return i, err
}

const updateVehiclePhoto = `-- name: UpdateVehiclePhoto :one
UPDATE vehicles SET "photoUrl" = $2 WHERE id = $1 RETURNING id, "resourceId", "plateNumber", brand, model, year, "currentOdometer", "categoryId", capacity, "photoUrl", energy_type
`

type UpdateVehiclePhotoParams struct {
	ID       int32          `json:"id"`
	PhotoUrl sql.NullString `json:"photoUrl"`
}

func (q *Queries) UpdateVehiclePhoto(ctx context.Context, arg UpdateVehiclePhotoParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, updateVehiclePhoto, arg.ID, arg.PhotoUrl)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.ResourceId,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometer,
		&i.CategoryId,
		&i.Capacity,
		&i.PhotoUrl,
		&i.EnergyType,
	)
	return i, err
}
