-- name: ListMaintenance :many
SELECT mr.*, r.name AS vehicle_name, v."plateNumber",
       u.name AS created_by_name
FROM maintenance_records mr
JOIN vehicles v ON v.id = mr."vehicleId"
JOIN resources r ON r.id = v."resourceId"
JOIN users u ON u.id = mr."recordedById"
WHERE (sqlc.narg(vehicle_id)::int IS NULL OR mr."vehicleId" = sqlc.narg(vehicle_id)::int)
ORDER BY mr."startDate" DESC
LIMIT $1 OFFSET $2;

-- name: CountMaintenance :one
SELECT COUNT(*) FROM maintenance_records
WHERE (sqlc.narg(vehicle_id)::int IS NULL OR "vehicleId" = sqlc.narg(vehicle_id)::int);

-- name: GetMaintenanceByID :one
SELECT mr.*, r.name AS vehicle_name, v."plateNumber",
       u.name AS created_by_name
FROM maintenance_records mr
JOIN vehicles v ON v.id = mr."vehicleId"
JOIN resources r ON r.id = v."resourceId"
JOIN users u ON u.id = mr."recordedById"
WHERE mr.id = $1 LIMIT 1;

-- name: CreateMaintenance :one
INSERT INTO maintenance_records (
    "vehicleId", "maintenanceTypeId", description, type, status,
    odometer, "totalCost", "vendorName", location, "startDate", "endDate", "completedAt", "proofPhotos", "recordedById", "isAutoGenerated"
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING *;

-- name: GetOngoingAutoMaintenanceByVehicle :one
-- Guards against creating duplicate auto-triggered maintenance records while one is still open.
SELECT * FROM maintenance_records
WHERE "vehicleId" = $1 AND "isAutoGenerated" = TRUE AND status != 'completed'
ORDER BY "createdAt" DESC LIMIT 1;

-- name: UpdateMaintenance :one
UPDATE maintenance_records
SET "vehicleId" = $2, "maintenanceTypeId" = $3, description = $4, type = $5, status = $6,
    odometer = $7, "totalCost" = $8, "vendorName" = $9, location = $10,
    "startDate" = $11, "endDate" = $12, "completedAt" = $13, "proofPhotos" = $14
WHERE id = $1 RETURNING *;

-- name: DeleteMaintenance :exec
DELETE FROM maintenance_records WHERE id = $1;
